function submitDspRegistration(formData) {
  const lock = LockService.getUserLock();
  lock.waitLock(30000);

  try {
    const userEmail = Session.getActiveUser().getEmail();
    const userName = userEmail.split('@')[0];
    const sheetName = "DSP 광고";
    let sheet = ss.getSheetByName(sheetName);

    // DSP의 모든 타입을 포함하는 전체 헤더 목록
    const masterHeaders = [
      'id', 'timestamp', 'registrant', 'status', 'manager', 'manager_timestamp', 'mail_thread_id', 'rejection_timestamp', 'rejection_reason', 'ad_id', 'completion_timestamp',
      'request_details', 'advertiser', 'campaign_name', 'ad_name', 'ad_type', 're_participation_type',
      'tracker', 'event_name', 'event_token',
      'event_condition_json', 'event_condition_json_type', 'event_condition_json_name', 'event_condition_json_value', 'event_condition_json_from', 'event_condition_json_to',
      'event_condition_individual', 'event_condition_individual_type', 'event_condition_individual_name', 'event_condition_individual_value', 'event_condition_individual_from', 'event_condition_individual_to',
      'landing_url', 'validity_period', 'total_volume', 'daily_volume', 'ad_rate', 'total_budget',
      'start_date', 'end_date', 'media_settings_json',
      // 구독형 필드
      'subscribe_target', 'image_recognition_id', 'account_id_1', 'account_id_2', 'account_id_3', 
      'guide_message', 'button_message', 'subscribe_page_url', 'example_image_url', 'aos_landing_url', 'ios_landing_url',
      'advertiser_link_token'
    ];

    if (!sheet) {
      sheet = ss.insertSheet(sheetName);
      sheet.appendRow(masterHeaders);
      sheet.getRange("1:1").setBackground("#f3f3f3").setFontWeight("bold");
      sheet.setFrozenRows(1);
    } else {
      // 시트가 이미 있는 경우, 누락된 컬럼이 있는지 확인하고 추가
      const currentHeaders = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
      const missingHeaders = masterHeaders.filter(h => !currentHeaders.includes(h));
      if (missingHeaders.length > 0) {
        sheet.getRange(1, currentHeaders.length + 1, 1, missingHeaders.length).setValues([missingHeaders]);
      }
    }

    const idPrefix = `dsp-${userName}-`;
    const nextId = getNextSequentialId(sheet, idPrefix);
    const uniqueId = `${idPrefix}${nextId}`;
    const formattedTimestamp = Utilities.formatDate(new Date(), "Asia/Seoul", "yyyy-MM-dd HH:mm:ss");

    const dspSubType = formData.dspSubType;
    let dataToSave = {};

    // DSP 타입에 따라 데이터 처리 분기
    if (dspSubType === 'DSP_구독형(EVENT)') {
      const subscriptionTarget = formData['구독 대상 이름'];
      dataToSave = {
        ad_type: 'CPA S2S_Event', // 고정값
        subscribe_target: subscriptionTarget,
        guide_message: formData['가이드 메세지'],
        button_message: formData['버튼 메세지'],
        subscribe_page_url: formData['구독 페이지 랜딩 URL'],
        example_image_url: formData['이미지 인식 예시 이미지']
      };

      const guideMessageMap = { '팔로우': '인스타그램 계정을 <팔로우> 해주세요', '유튜브 구독(채널메인)': '유튜브 계정을 <구독> 해주세요', '유튜브 구독(특정영상)': '유튜브 계정을 <구독> 해주세요' };
      const buttonMessageMap = { '팔로우': '팔로우 하러가기', '유튜브 구독(채널메인)': '구독 하러가기', '유튜브 구독(특정영상)': '구독 하러가기' };
      if (guideMessageMap[subscriptionTarget]) dataToSave.guide_message = guideMessageMap[subscriptionTarget];
      if (buttonMessageMap[subscriptionTarget]) dataToSave.button_message = buttonMessageMap[subscriptionTarget];
      
      const autoGeneratedTargets = ['유튜브 구독(채널메인)', '유튜브 구독(특정영상)', '팔로우'];
      if (autoGeneratedTargets.includes(subscriptionTarget)) {
        dataToSave.account_id_1 = formData['광고주 계정 식별자 1'];
        dataToSave.account_id_2 = formData['광고주 계정 식별자 2'];
        dataToSave.account_id_3 = formData['광고주 계정 식별자 3'];
        const identifiers = [dataToSave.account_id_1, dataToSave.account_id_2, dataToSave.account_id_3].filter(id => id && id.trim() !== '');
        
        if (identifiers.length > 0) {
          const identifierPart = `(${identifiers.map(id => `{${id}:text}`).join(' || ')})`;
          let conditionPart = '';
          switch (subscriptionTarget) {
            case '유튜브 구독(채널메인)': conditionPart = "({구독중:text} || {구독 중:text} || {구독충:text} || {subscribed:text}) && (!{캡쳐하기:text} && !{적립받기:text} && !{예시:text})"; break;
            case '유튜브 구독(특정영상)': conditionPart = "(({구독중:text} || {구독 중:text} || {구독충:text} || {subscribed:text}) || ({youtube_subscribe_alarm_all:customml} || {youtube_subscribe_alarm:customml} || {youtube_subscribe_no_alarm:customml})) && (!{캡쳐하기:text} && !{적립받기:text} && !{예시:text})"; break;
            case '팔로우': conditionPart = "({follow_white:customml} || {follow_black:customml} || {팔로잉 ~:text} || {팔로잉 아:text} || {팔로잉 v:text} || {팔로잉~:text} || {팔... ~:text} || {팔로... ~:text} || {팔...~:text} || {팔로...~:text} || {팔... :text} || {팔로... :text} || {팔...:text} || {팔로...:text} || {following v:text} || {following:text} || {팔로잉.*팔로잉:regex} || {following.*following:regex}) && (!{캡쳐하기:text} && !{적립받기:text} && !{예시:text})"; break;
          }
          if (conditionPart) dataToSave.image_recognition_id = `${identifierPart} && ${conditionPart}`;
        }
      } else {
        dataToSave.image_recognition_id = formData['이미지 인식에 사용할 식별자'];
      }

      if (subscriptionTarget === '팔로우' && dataToSave.subscribe_page_url) {
        const account = dataToSave.subscribe_page_url;
        dataToSave.aos_landing_url = `intent://instagram.com/_u/${account}#Intent;package=com.instagram.android;scheme=https;end`;
        dataToSave.ios_landing_url = `instagram://user?username=${account}`;
      }
    } else { // 'DSP_광고주연동' 타입
      dataToSave = {
        ad_type: formData['광고 타입'],
        tracker: formData['트래커'],
        event_name: formData['완료 이벤트 이름'],
        event_token: formData['이벤트 토큰'],
        event_condition_json: formData['완료 이벤트 조건(event_parameters JSON 파라미터)'],
        event_condition_json_type: formData['완료 이벤트 조건(event_parameters JSON 파라미터) 이벤트 타입'],
        event_condition_json_name: formData['완료 이벤트 조건(event_parameters JSON 파라미터) 이벤트 이름'],
        event_condition_json_value: formData['완료 이벤트 조건(event_parameters JSON 파라미터) value'],
        event_condition_json_from: formData['완료 이벤트 조건(event_parameters JSON 파라미터) from'],
        event_condition_json_to: formData['완료 이벤트 조건(event_parameters JSON 파라미터) to'],
        event_condition_individual: formData['완료 이벤트 조건 (개별 파라미터)'],
        event_condition_individual_type: formData['완료 이벤트 조건 (개별 파라미터) 파라미터 타입'],
        event_condition_individual_name: formData['완료 이벤트 조건 (개별 파라미터) 파라미터 이름'],
        event_condition_individual_value: formData['완료 이벤트 조건 (개별 파라미터) value'],
        event_condition_individual_from: formData['완료 이벤트 조건 (개별 파라미터) from'],
        event_condition_individual_to: formData['완료 이벤트 조건 (개별 파라미터) to']
      };
    }
    
    // 공통 필드 데이터 병합
    Object.assign(dataToSave, {
      id: uniqueId, timestamp: formattedTimestamp, registrant: userEmail, status: '등록 요청 완료',
      request_details: formData['요청사항'], advertiser: formData['광고주'], campaign_name: formData['캠페인명'],
      ad_name: formData['광고명'], re_participation_type: formData['재참여 타입'],
      landing_url: formData['랜딩 URL'] || dataToSave.aos_landing_url, // 팔로우 타입일 경우 AOS 랜딩을 기본값으로 사용
      validity_period: formData['완료 인정 유효기간 (일단위)'],
      total_volume: formData['총물량_unlimited'] ? '무제한' : formData['총물량'],
      daily_volume: formData['일물량_unlimited'] ? '무제한' : formData['일물량'],
      ad_rate: formData['광고 단가'], total_budget: formData['총예산'],
      start_date: formData['광고 시작일시'], end_date: formData['광고 종료일시_unlimited'] ? '무제한' : formData['광고 종료일시'],
      media_settings_json: formData['mediaSettingsJson'],
      advertiser_link_token: formData['광고주 연동 토큰'] || ''
    });

    const messageId = sendDspNotification(userEmail, uniqueId, dataToSave, dspSubType, formData.ccRecipients || '');
    dataToSave.mail_thread_id = messageId;
    
    const newRow = masterHeaders.map(header => dataToSave[header] || '');
    sheet.appendRow(newRow);

    return { success: true, message: `DSP 광고 등록 요청이 완료되었습니다. (ID: ${uniqueId})` };

  } catch (e) {
    console.error(`submitDspRegistration Error: ${e.toString()}`);
    return { success: false, message: `처리 중 오류가 발생했습니다: ${e.message}` };
  } finally {
    lock.releaseLock();
  }
}

function sendDspNotification(senderEmail, uniqueId, data, dspSubType, ccEmails) {
  let subject = '';
  if (dspSubType === 'DSP_구독형(EVENT)') {
    subject = `[DSP] ${data.campaign_name} ${data.ad_name}_${data.subscribe_target} (ID: ${uniqueId})`;
  } else {
    subject = `[DSP] ${data.campaign_name} ${data.ad_name} (ID: ${uniqueId})`;
  }
  
  // 모든 DSP 타입 필드를 포함하는 헤더 맵
  const headerMap = {
    request_details: '요청사항', advertiser: '광고주', campaign_name: '캠페인명', ad_name: '광고명', ad_type: '광고 타입', re_participation_type: '재참여 타입',
    subscribe_target: '구독 대상 이름', image_recognition_id: '이미지 인식 식별자', account_id_1: '계정 식별자 1', account_id_2: '계정 식별자 2', account_id_3: '계정 식별자 3',
    guide_message: '가이드 메세지', button_message: '버튼 메세지', subscribe_page_url: '구독 페이지 URL(인스타 계정)', example_image_url: '예시 이미지',
    aos_landing_url: 'AOS 랜딩 URL', ios_landing_url: 'IOS 랜딩 URL',
    advertiser_link_token: '광고주 연동 토큰',
    tracker: '트래커', event_name: '완료 이벤트 이름', event_token: '이벤트 토큰', 
    event_condition_json: '완료 이벤트 조건(JSON)',
    event_condition_json_type: 'JSON - 이벤트 타입', 
    event_condition_json_name: 'JSON - 이벤트 이름', 
    event_condition_json_value: 'JSON - value', 
    event_condition_json_from: 'JSON - from', 
    event_condition_json_to: 'JSON - to', 
    event_condition_individual: '완료 이벤트 조건(개별)',
    event_condition_individual_type: '개별 - 파라미터 타입', 
    event_condition_individual_name: '개별 - 파라미터 이름', 
    event_condition_individual_value: '개별 - value', 
    event_condition_individual_from: '개별 - from', 
    event_condition_individual_to: '개별 - to', 
    landing_url: '랜딩 URL', validity_period: '완료 인정 유효기간 (일단위)', total_volume: '총물량', daily_volume: '일물량', ad_rate: '광고 단가', total_budget: '총예산',
    start_date: '광고 시작일시', end_date: '광고 종료일시'
  };
  
  // 특수문자를 변환할 필드 목록
  const fieldsToEscape = ['request_details', 'guide_message', 'button_message'];

  let body = `<p>안녕하세요, 운영팀.</p>
              <p><b>${senderEmail}</b>님께서 DSP 광고 등록을 요청했습니다.</p>
              <p><b>등록 ID: ${uniqueId}</b></p>`;
  
  const confirmationUrl = `${ScriptApp.getService().getUrl()}?action=confirm_dsp&id=${uniqueId}`;
  body += `<div style="margin-top: 15px; margin-bottom: 15px; padding: 15px; border: 1px solid #ddd; border-radius: 5px; background-color: #f9f9f9;">
             <a href="${confirmationUrl}" style="background-color: #007bff; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px; margin-right: 10px;">[ 이 광고 담당하기 ]</a>
             <br><br>
             <div style="display: inline-block; vertical-align: middle;">
               <form action="${ScriptApp.getService().getUrl()}" method="get" target="_blank" style="margin:0; padding:0;">
                 <input type="hidden" name="action" value="complete_dsp">
                 <input type="hidden" name="id" value="${uniqueId}">
                 <input type="text" name="adId" placeholder="광고 ID 입력" required style="padding: 8px; border: 1px solid #ccc; border-radius: 4px; margin-right: 5px;">
                 <button type="submit" style="background-color: #28a745; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px; border: none; cursor: pointer;">[ 광고 등록 완료 처리 ]</button>
               </form>
             </div>
             <br><br>
             <a href="${ss.getUrl()}" style="color: #0056b3; text-decoration: none; margin-right: 15px;">스프레드시트 바로가기</a>
             <a href="${SYSTEM_URL}" style="color: #0056b3; text-decoration: none;">광고 등록 시스템 바로가기</a>
           </div>`;

  body += `<hr><h3>기본 정보</h3>
           <table align="left" cellpadding="8" style="border-collapse: collapse; border: 1px solid #e0e0e0; font-size: 12px; font-family: sans-serif;">`;
  
  for (const key in headerMap) {
    if (data[key]) {
      let value = String(data[key]);
      
      // 특정 필드의 특수문자를 HTML 엔티티로 변환
      if (fieldsToEscape.includes(key)) {
        value = value.replace(/</g, '&lt;').replace(/>/g, '&gt;');
      }
      
      let displayValue = value.replace(/\n/g, '<br>');
      if(key === 'event_condition_json' && value === 'TRUE') displayValue = '체크됨';
      if(key === 'event_condition_individual' && value === 'TRUE') displayValue = '체크됨';
      
      body += `<tr><td style="padding: 8px; border: 1px solid #e0e0e0; background-color: #f9f9f9; font-weight: bold; white-space: nowrap;">${headerMap[key]}</td><td style="padding: 8px; border: 1px solid #e0e0e0;">${displayValue}</td></tr>`;
    }
  }

  body += `</table><br style="clear:both;"><hr><h3>매체별 상세 설정</h3>`;
  
  if (data.media_settings_json) {
    try {
      const mediaSettings = JSON.parse(data.media_settings_json);
      if (mediaSettings.length > 0) {
        body += `<table align="left" cellpadding="8" style="border-collapse: collapse; border: 1px solid #e0e0e0; font-size: 12px; font-family: sans-serif;">
                   <thead><tr style="background-color:#f3f3f3;">
                     <th style="padding: 8px; border: 1px solid #e0e0e0;">매체명</th>
                     <th style="padding: 8px; border: 1px solid #e0e0e0;">매체 광고 단가</th>
                     <th style="padding: 8px; border: 1px solid #e0e0e0;">총물량</th>
                     <th style="padding: 8px; border: 1px solid #e0e0e0;">광고 시작일시</th>
                     <th style="padding: 8px; border: 1px solid #e0e0e0;">광고 종료일시</th>
                     <th style="padding: 8px; border: 1px solid #e0e0e0;">URL</th>
                   </tr></thead><tbody>`;
        mediaSettings.forEach(setting => {
          body += `<tr>
                     <td style="padding: 8px; border: 1px solid #e0e0e0;">${setting['매체명']}</td>
                     <td style="padding: 8px; border: 1px solid #e0e0e0;">${setting['단가']}</td>
                     <td style="padding: 8px; border: 1px solid #e0e0e0;">${setting['총물량']}</td>
                     <td style="padding: 8px; border: 1px solid #e0e0e0;">${setting['시작일시']}</td>
                     <td style="padding: 8px; border: 1px solid #e0e0e0;">${setting['종료일시']}</td>
                     <td style="padding: 8px; border: 1px solid #e0e0e0; word-break: break-all; white-space: nowrap;">${setting['URL'] || ''}</td>
                   </tr>`;
        });
        body += `</tbody></table>`;
      } else {
         body += `<p>선택된 매체가 없습니다.</p>`;
      }
    } catch (e) {
      body += `<p>매체 정보를 불러오는 데 실패했습니다.</p>`;
    }
  }

  GmailApp.sendEmail(ADMIN_EMAIL, subject, '', { htmlBody: body, cc: ccEmails });

  try {
    const slackMessage = { 'text': `${subject}` };
    const options = { 'method': 'post', 'contentType': 'application/json', 'payload': JSON.stringify(slackMessage) };
    UrlFetchApp.fetch(SLACK_WEBHOOK_URL, options);
  } catch (e) {
    console.error(`DSP 등록 슬랙 발송 실패 (ID: ${uniqueId}): ${e.toString()}`);
  }

  Utilities.sleep(2000); 
  const threads = GmailApp.search(`subject:"${subject}" in:sent`, 0, 1);
  if (threads && threads.length > 0) {
    const messages = threads[0].getMessages();
    if (messages && messages.length > 0) {
      return messages[0].getId();
    }
  }
  return null;
}

function getDspAllFormFields() {
  const fields = getDspFields();
  fields.dropdowns.advertisers = getDspAdvertisers();
  return fields;
}

function getDspAdvertisers() {
  return getExternalAdvertisersData().list;
}

/**
 * DSP 광고 ID를 기반으로 해당 행의 정보를 찾습니다.
 * @param {string} dspId - 찾을 DSP 고유 ID.
 * @returns {object|null} - 찾은 경우 {sheet, rowIndex, headers, rowData}, 못 찾은 경우 null.
 */
function findDspRowById(dspId) {
  const sheetName = "DSP 광고";
  const sheet = ss.getSheetByName(sheetName);
  if (!sheet) return null;

  const idColumn = sheet.getRange('A:A');
  const textFinder = idColumn.createTextFinder(dspId).matchEntireCell(true);
  const foundCell = textFinder.findNext();

  if (foundCell) {
    const rowIndex = foundCell.getRow();
    const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
    const rowData = sheet.getRange(rowIndex, 1, 1, sheet.getLastColumn()).getValues()[0];
    return { sheet, rowIndex, headers, rowData };
  }
  return null;
}

/**
 * DSP 광고 요청 건에 대한 담당자를 지정하고 알림을 보냅니다.
 * @param {string} dspId - DSP 요청 ID.
 * @param {string} approverEmail - 담당자 이메일.
 * @returns {string} 결과 메시지.
 */
function recordDspConfirmation(dspId, approverEmail) {
  const found = findDspRowById(dspId);
  if (!found) return `DSP ID: ${dspId} 건을 찾을 수 없습니다.`;
  
  const { sheet, rowIndex, headers, rowData } = found;
  const managerColIndex = headers.indexOf('manager');
  const statusColIndex = headers.indexOf('status');
  const threadIdColIndex = headers.indexOf('mail_thread_id');

  const currentStatus = rowData[statusColIndex];
  if (currentStatus === '스킵처리') {
    return `처리 실패: 이 DSP 요청 건(ID: ${dspId})은 이미 스킵 처리되어 담당자로 지정할 수 없습니다.`;
  }

  const currentManager = rowData[managerColIndex];
  if (currentManager && currentManager !== '') {
    return `처리 실패: 이 DSP 건(ID: ${dspId})은 이미 ${currentManager} 님이 담당하고 있습니다.`;
  }
  
  sheet.getRange(rowIndex, managerColIndex + 1).setValue(approverEmail);
  sheet.getRange(rowIndex, statusColIndex + 1).setValue('처리중');
  
  const timestampColIndex = headers.indexOf('manager_timestamp');
  if (timestampColIndex > -1) {
    const formattedTimestamp = Utilities.formatDate(new Date(), "Asia/Seoul", "yyyy-MM-dd HH:mm:ss");
    sheet.getRange(rowIndex, timestampColIndex + 1).setValue(formattedTimestamp);
  }

try {
    const searchQuery = `"${dspId}"`;
    const threads = GmailApp.search(searchQuery, 0, 1);

    if (threads && threads.length > 0) {
      threads[0].replyAll("", { 
        htmlBody: `<p>안녕하세요,</p><p><b>${approverEmail}</b> 님이 <b>DSP ID: ${dspId}</b> 건의 담당자로 지정되어 등록을 진행합니다.</p><p><a href="${SYSTEM_URL}">광고 등록 요청 시스템 바로가기</a></p><p>감사합니다.</p>`
      });
    } else {
      console.log(`DSP 담당자 지정 알림 실패: ${dspId} 관련 메일을 찾을 수 없습니다.`);
    }
  } catch (e) {
    console.error(`DSP 담당자 지정 알림 발송 중 오류: ${e.toString()}`);
  }
  // ▲▲▲ [수정] ▲▲▲
  
  return `DSP ID: ${dspId} 건의 담당자로 ${approverEmail}님이 지정되었습니다. 이 창은 닫아도 됩니다.`;
}

/**
 * DSP 광고 등록 완료 처리를 수행합니다.
 * @param {string} registrationId - DSP 요청 ID.
 * @param {string} adId - 등록된 실제 광고 ID.
 * @param {string} completerEmail - 완료 처리자 이메일.
 * @returns {object} 결과 객체 {success, message}.
 */
function processDspCompletion(registrationId, adId, completerEmail) {
  const found = findDspRowById(registrationId);
  if (!found) return { success: false, message: `DSP ID(${registrationId})를 찾을 수 없습니다.` };

  const { sheet, rowIndex, headers, rowData } = found;
  const statusColIndex = headers.indexOf('status');
  
  if (rowData[statusColIndex] === '등록 완료') {
    return { success: false, message: `이미 등록 완료 처리된 건입니다. (ID: ${registrationId})` };
  }
  
  const adIdColIndex = headers.indexOf('ad_id');
  const completionDateColIndex = headers.indexOf('completion_timestamp');
  const timestamp = Utilities.formatDate(new Date(), "Asia/Seoul", "yyyy-MM-dd HH:mm:ss");

  sheet.getRange(rowIndex, statusColIndex + 1).setValue('등록 완료');
  sheet.getRange(rowIndex, adIdColIndex + 1).setValue("'" + adId);
  sheet.getRange(rowIndex, completionDateColIndex + 1).setValue(timestamp);

  logUserAction(completerEmail, 'DSP 등록 완료 처리', {
    targetId: registrationId,
    message: `DSP ID '${registrationId}'를 광고 ID '${adId}'로 등록 완료 처리`
  });

  return { success: true, message: `DSP 건(ID: ${registrationId})이 성공적으로 완료 처리되었습니다. 이 창은 닫아도 됩니다.` };
}


function getDspAdDataById(dspId) {
  const found = findDspRowById(dspId);
  if (found) {
    const dspData = {};
    found.headers.forEach((header, index) => {
      let value = found.rowData[index];
      // 날짜/시간 데이터는 클라이언트에서 사용하기 쉬운 문자열 형태로 변환
      if (value instanceof Date) {
        try {
          value = Utilities.formatDate(value, "Asia/Seoul", "yyyy-MM-dd HH:mm");
        } catch(e) {
          value = '날짜 형식 오류';
        }
      }
      dspData[header] = value;
    });
    return dspData;
  }
  return null;
}


/**
 * DSP 광고 등록 요청을 반려 처리합니다.
 * @param {string} dspId - 반려할 DSP 요청 ID.
 * @param {string} reason - 반려 사유.
 * @returns {object} 처리 결과 객체.
 */
function processDspRejection(dspId, reason) {
  try {
    const rejectorEmail = Session.getActiveUser().getEmail();
    const found = findDspRowById(dspId);
    if (!found) {
      return { success: false, message: `DSP ID(${dspId})를 찾을 수 없습니다.` };
    }

    const { sheet, rowIndex, headers, rowData } = found;

    const statusColIndex = headers.indexOf('status');
    const rejectionDateColIndex = headers.indexOf('rejection_timestamp');
    const rejectionReasonColIndex = headers.indexOf('rejection_reason');
    const registrantColIndex = headers.indexOf('registrant');
    const threadIdColIndex = headers.indexOf('mail_thread_id');
    const campaignNameIndex = headers.indexOf('campaign_name');

    if ([statusColIndex, registrantColIndex, threadIdColIndex].includes(-1)) {
      return { success: false, message: '시트에서 필수 컬럼(status, registrant, mail_thread_id)을 찾을 수 없습니다.' };
    }

    // 1. 시트 상태 업데이트
    const timestamp = Utilities.formatDate(new Date(), "Asia/Seoul", "yyyy-MM-dd HH:mm:ss");
    sheet.getRange(rowIndex, statusColIndex + 1).setValue('반려');
    if (rejectionDateColIndex > -1) sheet.getRange(rowIndex, rejectionDateColIndex + 1).setValue(timestamp);
    if (rejectionReasonColIndex > -1) sheet.getRange(rowIndex, rejectionReasonColIndex + 1).setValue(reason);

    const registrantEmail = rowData[registrantColIndex];
    const threadId = rowData[threadIdColIndex];
    const campaignName = rowData[campaignNameIndex] || dspId;

    // 2. 메일 알림 발송 (전체 회신)
    if (registrantEmail && threadId) {
      const subject = `[광고 등록 시스템] 요청하신 DSP 광고(ID: ${dspId})가 반려되었습니다.`;
      let emailBody = `<p>안녕하세요, ${registrantEmail.split('@')[0]}님.</p>
                       <p>요청하신 DSP 광고(ID: <b>${dspId}</b>)가 아래와 같은 사유로 반려되었습니다.</p>`;
      if (reason) {
        emailBody += `<p style="margin-top:20px;"><b>반려 사유:</b></p>
                      <div style="padding: 12px; border: 1px solid #ddd; background-color: #f9f9f9; border-radius: 5px; margin-top: 5px;">
                        ${reason.replace(/\n/g, '<br>')}
                      </div>`;
      }
      emailBody += `<p style="margin-top:20px;">수정 후 재요청하시거나 담당자(${rejectorEmail})에게 문의해주세요.</p>
                    <p><a href="${SYSTEM_URL}">광고 등록 요청 시스템 바로가기</a></p>
                    <p>감사합니다.</p>`;
try {
        const searchQuery = `"${dspId}"`;
        const threads = GmailApp.search(searchQuery, 0, 1);

        if (threads && threads.length > 0) {
          threads[0].replyAll('', { htmlBody: emailBody, cc: registrantEmail });
        } else {
          console.warn(`DSP 반려: 스레드 찾기 실패(${dspId}). 새 메일 발송.`);
          GmailApp.sendEmail(registrantEmail, subject, '', { htmlBody: emailBody });
        }
      } catch (e) {
         console.error(`DSP 반려 메일 발송 실패 (ID: ${dspId}): ${e.toString()}`);
         GmailApp.sendEmail(registrantEmail, subject, '', { htmlBody: emailBody });
      }
      // ▲▲▲ [수정] ▲▲▲
    }

    // 3. 슬랙 알림 발송
    try {
      const slackMessage = { 'text': `[DSP 등록 반려] - ${campaignName}` };
      const options = { 'method': 'post', 'contentType': 'application/json', 'payload': JSON.stringify(slackMessage) };
      UrlFetchApp.fetch(SLACK_WEBHOOK_URL, options);
    } catch (e) {
      console.error(`DSP 반려 슬랙 발송 실패 (ID: ${dspId}): ${e.toString()}`);
    }

    logUserAction(rejectorEmail, 'DSP 반려 처리', {
      targetId: dspId,
      message: `DSP ID '${dspId}' 반려 처리. 사유: ${reason}`
    });

    return { success: true, message: `DSP ID(${dspId})가 성공적으로 반려 처리되었습니다.` };
  } catch (e) {
    console.error(`Error in processDspRejection: ${e.toString()}`);
    return { success: false, message: 'DSP 반려 처리 중 오류가 발생했습니다: ' + e.toString() };
  }
}


/**
 * DSP 광고 등록 요청을 스킵 처리합니다.
 * @param {string} dspId - 스킵할 DSP 요청 ID.
 * @returns {object} 처리 결과 객체.
 */
function processDspSkip(dspId) {
  try {
    const skipperEmail = Session.getActiveUser().getEmail();
    const found = findDspRowById(dspId);
    if (!found) {
      return { success: false, message: `DSP ID(${dspId})를 찾을 수 없습니다.` };
    }

    const { sheet, rowIndex, headers, rowData } = found;

    const statusColIndex = headers.indexOf('status');
    const threadIdColIndex = headers.indexOf('mail_thread_id');
    const campaignNameIndex = headers.indexOf('campaign_name');

    // 1. 시트 상태 업데이트
    sheet.getRange(rowIndex, statusColIndex + 1).setValue('스킵처리');

    const threadId = rowData[threadIdColIndex];
    const campaignName = rowData[campaignNameIndex] || dspId;

    // 2. 메일 알림 발송 (전체 회신)
    if (threadId) {
      try {
        const thread = GmailApp.getThreadById(threadId);
        if (thread) {
          thread.replyAll("", {
            htmlBody: `<p>안녕하세요,</p><p>요청하신 <b>DSP ID: ${dspId}</b> 건이 <b>스킵 처리</b>되었음을 알려드립니다.</p><p>감사합니다.</p><p>- 처리자: ${skipperEmail}</p>`,
          });
        }
      } catch (e) {
        console.error(`DSP 스킵 알림 메일 발송 실패(ID: ${dspId}): ${e.toString()}`);
      }
    }

    // 3. 슬랙 알림 발송
    try {
      const slackMessage = { 'text': `[DSP 등록 스킵] ${campaignName} (ID: ${dspId})` };
      const options = { 'method': 'post', 'contentType': 'application/json', 'payload': JSON.stringify(slackMessage) };
      UrlFetchApp.fetch(SLACK_WEBHOOK_URL, options);
    } catch (e) {
      console.error(`DSP 스킵 알림 슬랙 발송 실패 (ID: ${dspId}): ${e.toString()}`);
    }

    logUserAction(skipperEmail, 'DSP 스킵 처리', {
      targetId: dspId,
      message: `DSP ID '${dspId}' 스킵 처리`
    });

    return { success: true, message: `DSP ID(${dspId})가 성공적으로 스킵 처리되었습니다.` };
  } catch (e) {
    console.error(`Error in processDspSkip: ${e.toString()}`);
    return { success: false, message: 'DSP 스킵 처리 중 오류가 발생했습니다: ' + e.toString() };
  }
}


function submitDspModificationRequest(formData) {
  const lock = LockService.getUserLock();
  lock.waitLock(30000);

  try {
    const userEmail = Session.getActiveUser().getEmail();
    const sheetName = "DSP 수정";
    let sheet = ss.getSheetByName(sheetName);

    const masterHeaders = [
      'id', 'timestamp', 'registrant', 'status', 'manager', 'manager_timestamp', 'mail_thread_id', 'rejection_timestamp', 'rejection_reason', 'completion_timestamp',
      'request_details', 'target_campaign_id', 'target_campaign_name', 'target_ad_id', 'target_ad_name', 'ad_type', 'landing_url',
      'ad_rate', 'total_volume', 'daily_volume', 'start_date', 'end_date', 'event_id', 'event_guide_message', 'event_title_message', 'event_button_message', 'other_requests'
    ];

    if (!sheet) {
      sheet = ss.insertSheet(sheetName);
      sheet.appendRow(masterHeaders);
      sheet.getRange("1:1").setBackground("#f3f3f3").setFontWeight("bold").setFrozenRows(1);
    }

    const idPrefix = `dsp-mod-${userEmail.split('@')[0]}-`;
    const nextId = getNextSequentialId(sheet, idPrefix);
    const uniqueId = idPrefix + nextId;
    
    const formattedTimestamp = Utilities.formatDate(new Date(), "Asia/Seoul", "yyyy-MM-dd HH:mm:ss");

    const subject = `[DSP 수정 요청] ${formData['대상 광고명'].split('\n')[0]}_수정`;
    const messageId = sendDspModificationNotification(userEmail, uniqueId, subject, formData);
    
    const dataToSave = {
      id: uniqueId,
      timestamp: formattedTimestamp,
      registrant: userEmail,
      status: '수정 요청 완료',
      mail_thread_id: messageId,
      request_details: formData['요청사항'],
      target_campaign_id: formData['대상 캠페인ID'],
      target_campaign_name: formData['대상 캠페인명'],
      target_ad_id: formData['대상 광고ID'],
      target_ad_name: formData['대상 광고명'],
      ad_type: formData['광고 타입'],
      landing_url: formData['랜딩 URL'],
      ad_rate: formData['광고 단가'],
      total_volume: formData['총물량_unlimited'] ? '무제한' : formData['총물량'],
      daily_volume: formData['일물량_unlimited'] ? '무제한' : formData['일물량'],
      start_date: formData['광고 시작일시'],
      end_date: formData['광고 종료일시_unlimited'] ? '무제한' : formData['광고 종료일시'],
      event_id: formData['Event(구독형) 식별자'],
      event_guide_message: formData['Event(구독형) 가이드 메세지'],
      event_title_message: formData['Event(구독형) 타이틀 메세지'],
      event_button_message: formData['Event(구독형) 버튼 메세지'],
      other_requests: formData['기타 요청']
    };

    const newRow = masterHeaders.map(header => dataToSave[header] || '');
    sheet.appendRow(newRow);

    return { success: true, message: `DSP 수정 요청이 완료되었습니다. (ID: ${uniqueId})` };

  } catch (e) {
    console.error(`submitDspModificationRequest Error: ${e.toString()}`);
    return { success: false, message: `처리 중 오류가 발생했습니다: ${e.message}` };
  } finally {
    lock.releaseLock();
  }
}

function sendDspModificationNotification(senderEmail, modId, subject, data) {
  const confirmationUrl = `${ScriptApp.getService().getUrl()}?action=confirm_dsp_mod&id=${modId}`;
  const completionUrl = `${ScriptApp.getService().getUrl()}?action=complete_dsp_mod&id=${modId}`;
  const ccEmails = data.ccRecipients || '';

  let body = `<p>안녕하세요, 운영팀.</p>
              <p><b>${senderEmail}</b>님께서 DSP 광고 수정을 요청했습니다.</p>
              <p><b>수정 ID: ${modId}</b></p>
              <div style="margin-top: 15px; margin-bottom: 15px; padding: 15px; border: 1px solid #ddd; border-radius: 5px; background-color: #f9f9f9;">
                <a href="${confirmationUrl}" style="background-color: #007bff; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px; margin-right: 10px;">[ 이 수정 담당하기 ]</a>
                <a href="${completionUrl}" style="background-color: #28a745; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px;">[ 수정 완료 ]</a>
                <br><br>
                <a href="${ss.getUrl()}" style="color: #0056b3; text-decoration: none; margin-right: 15px;">스프레드시트 바로가기</a>
                <a href="${SYSTEM_URL}" style="color: #0056b3; text-decoration: none;">광고 등록 시스템 바로가기</a>
              </div>
              <hr><h3>요청 내용</h3>
              <table align="left" cellpadding="8" style="border-collapse: collapse; border: 1px solid #e0e0e0; font-size: 12px; font-family: sans-serif;">`;
  
  // formData 순회하며 테이블 생성 (기존 로직과 동일)
  const fieldOrder = [
    '요청사항', '대상 캠페인ID', '대상 캠페인명', '대상 광고ID', '대상 광고명',
    '광고 타입', '랜딩 URL', '광고 단가', '총물량', '일물량', 
    '광고 시작일시', '광고 종료일시', 
    'Event(구독형) 식별자', 'Event(구독형) 가이드 메세지', 
    'Event(구독형) 타이틀 메세지', 'Event(구독형) 버튼 메세지', '기타 요청'
  ];

  fieldOrder.forEach(key => {
    if (data[key]) {
      let value = data[key];
      // '총물량_unlimited'와 같은 보조 필드는 formData에 없으므로 직접 처리
      if (data[`${key}_unlimited`]) {
          value = '무제한';
      }
      body += `<tr><td style="padding: 8px; border: 1px solid #e0e0e0; background-color: #f9f9f9; font-weight: bold; white-space: nowrap;">${key}</td><td style="padding: 8px; border: 1px solid #e0e0e0;">${String(value).replace(/\n/g, '<br>')}</td></tr>`;
    }
  });
  body += `</table>`;

  GmailApp.sendEmail(ADMIN_EMAIL, subject, '', { htmlBody: body, cc: ccEmails });
  try {
    const slackMessage = { 'text': `${subject}` };
    const options = { 'method': 'post', 'contentType': 'application/json', 'payload': JSON.stringify(slackMessage) };
    UrlFetchApp.fetch(SLACK_WEBHOOK_URL, options);
  } catch (e) {
    console.error(`DSP 수정 요청 슬랙 발송 실패 (ID: ${modId}): ${e.toString()}`);
  }

  Utilities.sleep(2000);
  const threads = GmailApp.search(`subject:"${subject}" in:sent`, 0, 1);
  if (threads.length > 0) {
    return threads[0].getMessages()[0].getId();
  }
  return null;
}


/**
 * DSP 수정 ID를 기반으로 해당 행의 정보를 찾습니다.
 * @param {string} dspModId - 찾을 DSP 수정 요청 ID.
 * @returns {object|null} - 찾은 경우 {sheet, rowIndex, headers, rowData}, 못 찾은 경우 null.
 */
function findDspModRowById(dspModId) {
  const sheetName = "DSP 수정";
  const sheet = ss.getSheetByName(sheetName);
  if (!sheet) return null;

  const idColumn = sheet.getRange('A:A');
  const textFinder = idColumn.createTextFinder(dspModId).matchEntireCell(true);
  const foundCell = textFinder.findNext();

  if (foundCell) {
    const rowIndex = foundCell.getRow();
    const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
    const rowData = sheet.getRange(rowIndex, 1, 1, sheet.getLastColumn()).getValues()[0];
    return { sheet, rowIndex, headers, rowData };
  }
  return null;
}

/**
 * DSP 수정 요청 건에 대한 담당자를 지정하고 알림을 보냅니다.
 * @param {string} dspModId - DSP 수정 요청 ID.
 * @param {string} approverEmail - 담당자 이메일.
 * @returns {string} 결과 메시지.
 */
function recordDspModificationConfirmation(dspModId, approverEmail) {
  const found = findDspModRowById(dspModId);
  if (!found) return `DSP 수정 ID: ${dspModId} 건을 찾을 수 없습니다.`;
  
  const { sheet, rowIndex, headers, rowData } = found;
  const managerColIndex = headers.indexOf('manager');
  const statusColIndex = headers.indexOf('status');
  const threadIdColIndex = headers.indexOf('mail_thread_id');

  if (rowData[managerColIndex] && rowData[managerColIndex] !== '') {
    return `처리 실패: 이 DSP 수정 건(ID: ${dspModId})은 이미 ${rowData[managerColIndex]} 님이 담당하고 있습니다.`;
  }
  
  sheet.getRange(rowIndex, managerColIndex + 1).setValue(approverEmail);
  sheet.getRange(rowIndex, statusColIndex + 1).setValue('처리중');
  
  const timestampColIndex = headers.indexOf('manager_timestamp');
  if (timestampColIndex > -1) {
    const formattedTimestamp = Utilities.formatDate(new Date(), "Asia/Seoul", "yyyy-MM-dd HH:mm:ss");
    sheet.getRange(rowIndex, timestampColIndex + 1).setValue(formattedTimestamp);
  }

  const threadId = rowData[threadIdColIndex];
  if (threadId) {
    try {
      const thread = GmailApp.getThreadById(threadId);
      if (thread) {
        thread.replyAll("", { 
          htmlBody: `<p>안녕하세요,</p><p><b>${approverEmail}</b> 님이 <b>DSP 수정 ID: ${dspModId}</b> 건의 담당자로 지정되어 수정을 진행합니다.</p><p><a href="${SYSTEM_URL}">광고 등록 요청 시스템 바로가기</a></p><p>감사합니다.</p>`
        });
      }
    } catch (e) {
      console.error(`DSP 수정 담당자 지정 알림 실패: ${e.toString()}`);
    }
  }
  
  return `DSP 수정 ID: ${dspModId} 건의 담당자로 ${approverEmail}님이 지정되었습니다. 이 창은 닫아도 됩니다.`;
}

/**
 * DSP 수정 요청 완료 처리를 수행합니다.
 * @param {string} dspModId - DSP 수정 요청 ID.
 * @param {string} completerEmail - 완료 처리자 이메일.
 * @returns {object} 결과 객체 {success, message}.
 */
function processDspModificationCompletion(dspModId, completerEmail) {
  const found = findDspModRowById(dspModId);
  if (!found) return { success: false, message: `DSP 수정 ID(${dspModId})를 찾을 수 없습니다.` };

  const { sheet, rowIndex, headers, rowData } = found;
  const statusColIndex = headers.indexOf('status');
  
  if (rowData[statusColIndex] === '수정 완료') {
    return { success: false, message: `이미 수정 완료 처리된 건입니다. (ID: ${dspModId})` };
  }
  
  const completionDateColIndex = headers.indexOf('completion_timestamp');
  const timestamp = Utilities.formatDate(new Date(), "Asia/Seoul", "yyyy-MM-dd HH:mm:ss");

  sheet.getRange(rowIndex, statusColIndex + 1).setValue('수정 완료');
  if (completionDateColIndex > -1) {
    sheet.getRange(rowIndex, completionDateColIndex + 1).setValue(timestamp);
  }

  logUserAction(completerEmail, 'DSP 수정 완료 처리', {
    targetId: dspModId,
    message: `DSP 수정 ID '${dspModId}' 완료 처리`
  });

  return { success: true, message: `DSP 수정 건(ID: ${dspModId})이 성공적으로 완료 처리되었습니다. 이 창은 닫아도 됩니다.` };
}


/**
 * DSP 수정 요청을 스킵 처리합니다.
 * @param {string} dspModId - 스킵할 DSP 수정 요청 ID.
 * @returns {object} 처리 결과 객체.
 */
function processDspModificationSkip(dspModId) {
  try {
    const skipperEmail = Session.getActiveUser().getEmail();
    const found = findDspModRowById(dspModId); // DSP 수정 시트에서 ID 검색
    if (!found) {
      return { success: false, message: `DSP 수정 ID(${dspModId})를 찾을 수 없습니다.` };
    }

    const { sheet, rowIndex, headers, rowData } = found;

    const statusColIndex = headers.indexOf('status');
    const threadIdColIndex = headers.indexOf('mail_thread_id');
    const adNameIndex = headers.indexOf('target_ad_name');

    // 1. 시트 상태를 '스킵처리'로 업데이트
    sheet.getRange(rowIndex, statusColIndex + 1).setValue('스킵처리');

    const threadId = rowData[threadIdColIndex];
    const adName = rowData[adNameIndex] || dspModId;
    
    // ▼▼▼ [수정] adName을 String()으로 감싸서 타입을 강제로 텍스트로 변환 ▼▼▼
    const subject = String(adName).split('\n')[0];
    // ▲▲▲ [수정] ▲▲▲

    // 2. 원본 요청 메일 스레드에 스킵 처리되었음을 회신
    if (threadId) {
      try {
        const thread = GmailApp.getThreadById(threadId);
        if (thread) {
          thread.replyAll("", {
            htmlBody: `<p>안녕하세요,</p><p>요청하신 <b>DSP 수정 ID: ${dspModId}</b> 건이 <b>스킵 처리</b>되었음을 알려드립니다.</p><p>감사합니다.</p><p>- 처리자: ${skipperEmail}</p>`,
          });
        }
      } catch (e) {
        console.error(`DSP 수정 스킵 알림 메일 발송 실패(ID: ${dspModId}): ${e.toString()}`);
      }
    }

    // 3. 슬랙으로 알림 발송
    try {
      const slackMessage = { 'text': `[DSP 수정 스킵] ${subject} (ID: ${dspModId})` };
      const options = { 'method': 'post', 'contentType': 'application/json', 'payload': JSON.stringify(slackMessage) };
      UrlFetchApp.fetch(SLACK_WEBHOOK_URL, options);
    } catch (e) {
      console.error(`DSP 수정 스킵 알림 슬랙 발송 실패 (ID: ${dspModId}): ${e.toString()}`);
    }

    // 4. 활동 로그 기록
    logUserAction(skipperEmail, 'DSP 수정 스킵 처리', {
      targetId: dspModId,
      message: `DSP 수정 ID '${dspModId}' 스킵 처리`
    });

    return { success: true, message: `DSP 수정 ID(${dspModId})가 성공적으로 스킵 처리되었습니다.` };
  } catch (e) {
    console.error(`Error in processDspModificationSkip: ${e.toString()}`);
    return { success: false, message: 'DSP 수정 스킵 처리 중 오류가 발생했습니다: ' + e.toString() };
  }
}


/**
 * DSP 수정 ID를 기반으로 해당 행의 데이터를 객체 형태로 가져옵니다.
 * @param {string} dspModId - 조회할 DSP 수정 요청 ID.
 * @returns {object|null} - 찾은 데이터 객체 또는 null.
 */
function getDspModificationDataById(dspModId) {
  const found = findDspModRowById(dspModId);
  if (found) {
    const data = {};
    found.headers.forEach((header, index) => {
      let value = found.rowData[index];
      // 날짜/시간 데이터는 클라이언트에서 사용하기 쉬운 문자열 형태로 변환
      if (value instanceof Date) {
        try {
          value = Utilities.formatDate(value, "Asia/Seoul", "yyyy-MM-dd HH:mm");
        } catch(e) {
          value = '날짜 형식 오류';
        }
      }
      data[header] = value;
    });
    return data;
  }
  return null;
}


/**
 * DSP 수정 요청을 반려 처리합니다.
 * @param {string} dspModId - 반려할 DSP 수정 요청 ID.
 * @param {string} reason - 반려 사유.
 * @returns {object} 처리 결과 객체.
 */
function processDspModificationRejection(dspModId, reason) {
  try {
    const rejectorEmail = Session.getActiveUser().getEmail();
    const found = findDspModRowById(dspModId);
    if (!found) {
      return { success: false, message: `DSP 수정 ID(${dspModId})를 찾을 수 없습니다.` };
    }

    const { sheet, rowIndex, headers, rowData } = found;

    const statusColIndex = headers.indexOf('status');
    const rejectionDateColIndex = headers.indexOf('rejection_timestamp');
    const rejectionReasonColIndex = headers.indexOf('rejection_reason');
    const registrantColIndex = headers.indexOf('registrant');
    const threadIdColIndex = headers.indexOf('mail_thread_id');
    const adNameIndex = headers.indexOf('target_ad_name');

    // 1. 시트 상태 업데이트
    const timestamp = Utilities.formatDate(new Date(), "Asia/Seoul", "yyyy-MM-dd HH:mm:ss");
    sheet.getRange(rowIndex, statusColIndex + 1).setValue('반려');
    if (rejectionDateColIndex > -1) sheet.getRange(rowIndex, rejectionDateColIndex + 1).setValue(timestamp);
    if (rejectionReasonColIndex > -1) sheet.getRange(rowIndex, rejectionReasonColIndex + 1).setValue(reason);

    const registrantEmail = rowData[registrantColIndex];
    const threadId = rowData[threadIdColIndex];
    const adName = rowData[adNameIndex] || dspModId;

    // 2. 메일 알림 발송 (전체 회신)
    if (registrantEmail && threadId) {
      const subject = `[광고 등록 시스템] 요청하신 DSP 수정(ID: ${dspModId})이 반려되었습니다.`;
      let emailBody = `<p>안녕하세요, ${registrantEmail.split('@')[0]}님.</p>
                       <p>요청하신 DSP 수정(ID: <b>${dspModId}</b>)이 아래와 같은 사유로 반려되었습니다.</p>`;
      if (reason) {
        emailBody += `<p style="margin-top:20px;"><b>반려 사유:</b></p>
                      <div style="padding: 12px; border: 1px solid #ddd; background-color: #f9f9f9; border-radius: 5px; margin-top: 5px;">
                        ${reason.replace(/\n/g, '<br>')}
                      </div>`;
      }
      emailBody += `<p style="margin-top:20px;">수정 후 재요청하시거나 담당자(${rejectorEmail})에게 문의해주세요.</p>
                    <p><a href="${SYSTEM_URL}">광고 등록 요청 시스템 바로가기</a></p>
                    <p>감사합니다.</p>`;
      try {
        const thread = GmailApp.getThreadById(threadId);
        if (thread) {
          thread.replyAll('', { htmlBody: emailBody, cc: registrantEmail });
        }
      } catch (e) {
         console.error(`DSP 수정 반려 메일 발송 실패 (ID: ${dspModId}): ${e.toString()}`);
         GmailApp.sendEmail(registrantEmail, subject, '', { htmlBody: emailBody });
      }
    }

    // 3. 슬랙 알림 발송
    try {
      const slackMessage = { 'text': `[DSP 수정 반려] - ${String(adName).split('\n')[0]} (ID: ${dspModId})` };
      const options = { 'method': 'post', 'contentType': 'application/json', 'payload': JSON.stringify(slackMessage) };
      UrlFetchApp.fetch(SLACK_WEBHOOK_URL, options);
    } catch (e) {
      console.error(`DSP 수정 반려 슬랙 발송 실패 (ID: ${dspModId}): ${e.toString()}`);
    }

    // 4. 활동 로그 기록
    logUserAction(rejectorEmail, 'DSP 수정 반려 처리', {
      targetId: dspModId,
      message: `DSP 수정 ID '${dspModId}' 반려 처리. 사유: ${reason}`
    });

    return { success: true, message: `DSP 수정 ID(${dspModId})가 성공적으로 반려 처리되었습니다.` };
  } catch (e) {
    console.error(`Error in processDspModificationRejection: ${e.toString()}`);
    return { success: false, message: 'DSP 수정 반려 처리 중 오류가 발생했습니다: ' + e.toString() };
  }
}