function getAllFormFields() {
  const advertiserData = getExternalAdvertisersData(); 
  const advertisers = advertiserData.list;
  const advertiserCategoryMap = advertiserData.map;
  const clients = getExternalClients();

  const newCategoryOptions = ['게임', '관공서/단체','교육/취업','금융','내부','비즈니스/전문서비스','자동차/수송','식품/음료','엔터테인먼트','유통','전자/가전','건강/의료','의류/패션','화장품/미용','ICT (network)','건설/부동산','여행/교통','결혼/출산/육아','생활용품','레저스포츠/취미','주류/담배','기타','문화/공연/영화','커머스','ICT (communication)'];
  const taggingOptions = ['가입형','교환형','구매형','네이버뉴스','네이버스토어','네이버포스트','네이버플레이스','라방시청','라방알림','로그인형','바이럴','발급형','보험가입형','블로그','사전예약','설치형','스토어알림','실행형','유료서비스','유튜브','이벤트배너','인스타','인하우스','참여형','체험형','카카오채널','트위터','틱톡','페이스북','포인트교환','플레이스'];

  const detailInfoDefault = `・ 이벤트 참여 완료 시 쿠키가 지급되며, MY > 내쿠키에서 지급 여부를 확인할 수 있습니다.
・ 쿠키 사용 유효기간은 지급받은 쿠키 개수에 따라 다릅니다.
 1~49개 = 유효기간 7일
 50 ~ 99개 = 유효기간 14일
 100 ~ 299개 = 유효기간 30일
 300 ~ 599개 = 유효기간 60일
 600 ~ 799개 = 유효기간 90일
 800 ~ 999개 = 유효기간 120일
・ 지급받은 쿠키는 웹툰/시리즈에서 사용할 수 있습니다.
・ 네트워크 장애 발생 시, 이벤트 참여 후 쿠키 지급까지 시간이 다소 지연될 수 있습니다.`;

  const fields = {
  '광고': {
    'CPA S2S': {
    headerOrder: [ '특이사항 메모장', '재참여 타입', '광고주', '브랜드', '액션명', '태깅', '카테고리', '거래처', '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', '광고주 연동 토큰 값', '집행매체1', '집행매체2', 'OS', '광고 정산 타입', '광고 액션 타입', '예산', '단가', '총물량_통합', '총물량_AOS', '총물량_IOS', '일물량_통합', '일물량_AOS', '일물량_IOS', '리워드', '광고 집행 시작', '광고 집행 종료', '광고 참여 시작 후 완료 인정 유효기간 (일단위)', '최소 결제 금액', 'URL_기본', 'URL_AOS', 'URL_IOS', 'URL_PC', '소재', '후지급', '라이브 시작 시간', '라이브 종료 시간', 'adid 타겟팅 모수파일', '데모타겟1', '데모타겟2', '앱 패키지명', '광고주 앱 이름', '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '문구 - 서브1 하단', '문구 - 서브2', '목록리워드', '노출 대상' ],
   fields: [
    { name: '특이사항 메모장', type: 'textarea', required: false },
    { name: '태깅', type: 'select', options: taggingOptions, required: true },
    { name: '재참여 타입', type: 'select', options: ['단일', '일일 한번', '무한'], required: true },
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: '브랜드', type: 'text', required: true },
    { name: '액션명', type: 'text', required: true },
    { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
    { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
    { name: '리포트 타입', type: 'select', options: ['일반', 'CPP', 'CPS', 'CPQ', 'CPC', 'CPM', 'CPS-RewardFail'], required: true },
    { name: '광고주 CS 담당자 이름', type: 'text', required: false },
    { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
    { name: '광고주 연동 토큰 값', type: 'text', required: true },
    { name: '집행매체1', type: 'select', options: ['쿠키오븐', '애디슨 네트워크', '네이버페이'], required: true },
    { name: '집행매체2_쿠키오븐', label: '집행매체2', type: 'select', options: ['전체', '웹툰', '시리즈'], required: true, dependency: { field: '집행매체1', showsOn: '쿠키오븐' } },
    { name: '집행매체2_애디슨', label: '집행매체2', type: 'select', options: ['전체', '특정 매체만 진행'], required: true, dependency: { field: '집행매체1', showsOn: '애디슨 네트워크' } },
    { name: '집행매체2_애디슨_특정', label: '특정 매체명', type: 'text', placeholder: '특정 매체명 입력', required: true, dependency: { field: '집행매체2_애디슨', showsOn: '특정 매체만 진행' } },
    { name: 'OS_DROPDOWN', label: 'OS', type: 'select', options: ['전체', 'AOS', 'IOS'], required: true, dependency: { field: '집행매체1', showsOn: ['쿠키오븐', '애디슨 네트워크'] } },
    { name: 'OS_CHECKBOX', label: 'OS', type: 'checkbox', options: ['AOS', 'IOS', 'AOS+IOS', 'PC'], required: true, dependency: { field: '집행매체1', showsOn: '네이버페이' } },
    { name: '광고 정산 타입', type: 'select', options: ['CPI', 'CPE', 'CPA_SNS', 'CPA_사전예약', 'CPA_회원가입', 'CPA_금융', 'CPQ', 'CPS', 'CPC', '기타'], required: true },
    { name: '광고 액션 타입', type: 'select', options: ['APP', 'WEB'], required: true },
     { name: '예산', type: 'number-unlimited', required: true },
    { name: '단가', type: 'number', required: true },
    { name: '총물량', type: 'volume_split', required: true },
    { name: '일물량', type: 'volume_split', required: true },
    { name: '리워드', type: 'text', required: true, placeholder: '매체와 단가 입력 시 자동 계산', dependency: { field: '집행매체1', hidesOn: ['애디슨 네트워크'] } },
    { name: '광고 집행 시작', type: 'datetime-local', required: true },
    { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '광고 참여 시작 후 완료 인정 유효기간 (일단위)', type: 'text', required: true, defaultValue: '1'  },
    { name: '최소 결제 금액', type: 'text', required: false },
    { name: 'URL_기본', type: 'text', required: false },
    { name: 'URL_AOS', type: 'text', required: false },
    { name: 'URL_IOS', type: 'text', required: false },
    { name: 'URL_PC', type: 'text', required: false },
    { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' },
    { name: '후지급', type: 'text', required: false },
    { name: '라이브 시작 시간', type: 'text', required: false, defaultValue: '00:00' },
    { name: '라이브 종료 시간', type: 'text', required: false, defaultValue: '24:00' },
    { name: 'adid 타겟팅 모수파일', type: 'text', required: false, placeholder: 'adid 파일 구글 드라이브 링크 입력'  },
    { name: '데모타겟1', type: 'select', options: ['모두', '남성', '여성'], required: false },
    { name: '데모타겟2', type: 'text', required: false, placeholder: '연령 (예: 20-39)'},
    { name: '앱 패키지명', type: 'text', required: false },
    { name: '광고주 앱 이름', type: 'text', required: false },
    { name: '문구 - 타이틀', type: 'text', required: true },
    { name: '문구 - 서브', type: 'text', required: true },
    { name: '문구 - 서브1 상단', type: 'text', required: true },
    { name: '문구 - 서브1 하단', type: 'text', required: false },
    { name: '문구 - 서브2', type: 'textarea', required: true },
     { name: '목록리워드', type: 'text', required: false },
    { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true }
  ]
},
    'CPI': {
      headerOrder: [ '특이사항 메모장', '광고주', '브랜드', '액션명', '카테고리', '거래처', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', '집행매체1', '집행매체2', 'OS', '예산', '단가', '총물량', '리워드', '일물량', '광고 집행 시작', '광고 집행 종료', 'URL', '소재', '후지급', '라이브 시작 시간', '라이브 종료 시간', 'adid 타겟팅 모수파일', '데모타겟1', '데모타겟2', '앱 패키지명', '광고주 앱 이름', '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '문구 - 서브2', '노출 대상' ],
      fields: [ { name: '특이사항 메모장', type: 'textarea', required: false }, { name: '태깅', type: 'select', options: ['설치형'], defaultValue: '설치형', readonly: true, required: true }, { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true }, { name: '브랜드', type: 'text', required: true }, { name: '액션명', type: 'text', required: true }, { name: '카테고리', type: 'select', options: newCategoryOptions, required: true }, { name: '거래처', type: 'select', optionsKey: 'clients', required: true }, { name: '광고주 CS 담당자 이름', type: 'text', required: false }, { name: '광고주 CS 담당자 이메일', type: 'text', required: false }, { name: '집행매체1', type: 'select', options: ['쿠키오븐', '애디슨 네트워크', '네이버페이'], required: true }, { name: '집행매체2_쿠키오븐', label: '집행매체2', type: 'select', options: ['전체', '웹툰', '시리즈'], required: true, dependency: { field: '집행매체1', showsOn: '쿠키오븐' } }, { name: '집행매체2_애디슨', label: '집행매체2', type: 'select', options: ['전체', '특정 매체만 진행'], required: true, dependency: { field: '집행매체1', showsOn: '애디슨 네트워크' } }, { name: '집행매체2_애디슨_특정', label: '특정 매체명', type: 'text', placeholder: '특정 매체명 입력', required: true, dependency: { field: '집행매체2_애디슨', showsOn: '특정 매체만 진행' } }, { name: 'OS_DROPDOWN', label: 'OS', type: 'select', options: ['전체', 'AOS', 'IOS'], required: true, dependency: { field: '집행매체1', showsOn: ['쿠키오븐', '애디슨 네트워크'] } }, { name: 'OS_CHECKBOX', label: 'OS', type: 'checkbox', options: ['AOS', 'IOS', 'AOS+IOS', 'PC'], required: true, dependency: { field: '집행매체1', showsOn: '네이버페이' } }, 
      { name: '예산', type: 'number-unlimited', required: true },
      { name: '단가', type: 'number', required: true }, { name: '총물량', type: 'number-unlimited', required: true }, { name: '리워드', type: 'text', required: true, placeholder: '매체와 단가 입력 시 자동 계산', dependency: { field: '집행매체1', hidesOn: ['애디슨 네트워크'] } }, { name: '일물량', type: 'text', required: true }, { name: '광고 집행 시작', type: 'datetime-local', required: true }, { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true }, { name: 'URL', type: 'text', required: true }, { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' }, { name: '후지급', type: 'text', required: false }, { name: '라이브 시작 시간', type: 'text', required: false, defaultValue: '00:00' }, { name: '라이브 종료 시간', type: 'text', required: false, defaultValue: '24:00' }, { name: 'adid 타겟팅 모수파일', type: 'text', required: false, placeholder: 'adid 파일 구글 드라이브 링크 입력' }, { name: '데모타겟1', type: 'select', options: ['모두', '남성', '여성'], required: false }, { name: '데모타겟2', type: 'text', required: false, placeholder: '연령 (예: 20-39)'}, { name: '앱 패키지명', type: 'text', required: true }, { name: '광고주 앱 이름', type: 'text', required: true }, { name: '문구 - 타이틀', type: 'text', required: true }, { name: '문구 - 서브', type: 'text', required: true }, { name: '문구 - 서브1 상단', type: 'text', required: true }, { name: '문구 - 서브2', type: 'textarea', required: true }, { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true }, ]
    },
  'CPA TRACKER': {
  headerOrder: [ 
    '특이사항 메모장', '재참여 타입', '광고주', '브랜드', '액션명', '카테고리', 
    '거래처', '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', 
    '광고주 연동 토큰 값', '집행매체1', '집행매체2', 'OS', '광고 정산 타입', 
    '광고 액션 타입', '예산', '단가', '총물량_통합', '총물량_AOS', '총물량_IOS', 
    '일물량_통합', '일물량_AOS', '일물량_IOS', '리워드', '광고 집행 시작', 
    '광고 집행 종료', '광고 참여 시작 후 완료 인정 유효기간 (일단위)', '트래커', '완료 이벤트 이름', 
    '완료 이벤트 조건(JSON)-이벤트 타입', '완료 이벤트 조건(JSON)-이벤트 이름', '완료 이벤트 조건(JSON)-value', '완료 이벤트 조건(JSON)-from', '완료 이벤트 조건(JSON)-to', 
    '완료 이벤트 조건(개별)-파라미터 타입', '완료 이벤트 조건(개별)-파라미터 이름', '완료 이벤트 조건(개별)-value', '완료 이벤트 조건(개별)-from', '완료 이벤트 조건(개별)-to', 
    '최소 결제 금액', 'URL_기본', 'URL_AOS', 'URL_IOS', 'URL_PC', '소재', '후지급', 
    '라이브 시작 시간', '라이브 종료 시간', 'adid 타겟팅 모수파일', '데모타겟1', '데모타겟2', 
    '앱 패키지명', '광고주 앱 이름', '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', 
    '문구 - 서브1 하단', '문구 - 서브2', '목록리워드', '노출 대상' // ▼▼▼ [수정] 3개 항목 추가 ▼▼▼
  ],
  fields: [
    { name: '특이사항 메모장', type: 'textarea', required: false },
    { name: '태깅', type: 'select', options: taggingOptions, required: true },
    { name: '재참여 타입', type: 'select', options: ['단일', '일일 한번', '무한'], required: true },
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: '브랜드', type: 'text', required: true },
    { name: '액션명', type: 'text', required: true },
    { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
    { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
    { name: '리포트 타입', type: 'select', options: ['일반', 'CPP', 'CPS', 'CPQ', 'CPC', 'CPM', 'CPS-RewardFail'], required: true },
    { name: '광고주 CS 담당자 이름', type: 'text', required: false },
    { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
    { name: '광고주 연동 토큰 값', type: 'text', required: false },
    { name: '집행매체1', type: 'select', options: ['쿠키오븐', '애디슨 네트워크', '네이버페이'], required: true },
    { name: '집행매체2_쿠키오븐', label: '집행매체2', type: 'select', options: ['전체', '웹툰', '시리즈'], required: true, dependency: { field: '집행매체1', showsOn: '쿠키오븐' } },
    { name: '집행매체2_애디슨', label: '집행매체2', type: 'select', options: ['전체', '특정 매체만 진행'], required: true, dependency: { field: '집행매체1', showsOn: '애디슨 네트워크' } },
    { name: '집행매체2_애디슨_특정', label: '특정 매체명', type: 'text', placeholder: '특정 매체명 입력', required: true, dependency: { field: '집행매체2_애디슨', showsOn: '특정 매체만 진행' } },
    { name: 'OS_DROPDOWN', label: 'OS', type: 'select', options: ['전체', 'AOS', 'IOS'], required: true, dependency: { field: '집행매체1', showsOn: ['쿠키오븐', '애디슨 네트워크'] } },
    { name: 'OS_CHECKBOX', label: 'OS', type: 'checkbox', options: ['AOS', 'IOS', 'AOS+IOS', 'PC'], required: true, dependency: { field: '집행매체1', showsOn: '네이버페이' } },
    { name: '광고 정산 타입', type: 'select', options: ['CPI', 'CPE', 'CPA_SNS', 'CPA_사전예약', 'CPA_회원가입', 'CPA_금융', 'CPQ', 'CPS', 'CPC', '기타'], required: true },
      { name: '광고 액션 타입', type: 'select', options: ['APP', 'WEB'], required: true },
  
    { name: '예산', type: 'number-unlimited', required: true },
    { name: '단가', type: 'number', required: true },
    { name: '총물량', type: 'volume_split', required: true },
    { name: '일물량', type: 'volume_split', required: true },
    { name: '리워드', type: 'text', required: true, placeholder: '매체와 단가 입력 시 자동 계산', dependency: { field: '집행매체1', hidesOn: ['애디슨 네트워크'] } },
    { name: '광고 집행 시작', type: 'datetime-local', required: true },
    { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '광고 참여 시작 후 완료 인정 유효기간 (일단위)', type: 'text', required: false, defaultValue: '1'  },
    { name: '트래커', type: 'select', options: ['Tune', 'Adbrix', 'Adjust', 'AppsFlyer', 'Kochava', 'Singular', 'Wisetracker', 'Branch', 'Airbridge', 'Adbrix Remaster', 'Ebay Linkrew'], required: true },
    { name: '완료 이벤트 이름', type: 'text', required: true },
    { name: '완료 이벤트 조건(JSON)', type: 'group_checkbox', label: '완료 이벤트 조건(event_parameters JSON 파라미터)' },
    { name: '완료 이벤트 조건(JSON)-이벤트 타입', type: 'select', options: ['Value', 'Range', 'not_allowed_value'], required: true, dependency: { field: '완료 이벤트 조건(JSON)', showsOn: true } },
    { name: '완료 이벤트 조건(JSON)-이벤트 이름', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(JSON)', showsOn: true } },
    { name: '완료 이벤트 조건(JSON)-value', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(JSON)', showsOn: true } },
    { name: '완료 이벤트 조건(JSON)-from', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(JSON)', showsOn: true } },
    { name: '완료 이벤트 조건(JSON)-to', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(JSON)', showsOn: true } },
    { name: '완료 이벤트 조건(개별)', type: 'group_checkbox', label: '완료 이벤트 조건 (개별 파라미터)' },
    { name: '완료 이벤트 조건(개별)-파라미터 타입', type: 'select', options: ['Value', 'Range', 'not_allowed_value'], required: true, dependency: { field: '완료 이벤트 조건(개별)', showsOn: true } },
    { name: '완료 이벤트 조건(개별)-파라미터 이름', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(개별)', showsOn: true } },
    { name: '완료 이벤트 조건(개별)-value', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(개별)', showsOn: true } },
    { name: '완료 이벤트 조건(개별)-from', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(개별)', showsOn: true } },
    { name: '완료 이벤트 조건(개별)-to', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(개별)', showsOn: true } },
    // ▼▼▼ [수정] '최소 결제 금액' 필드 추가 ▼▼▼
    { name: '최소 결제 금액', type: 'text', required: false },
    // ▲▲▲ [수정] ▲▲▲
    { name: 'URL_기본', type: 'text', required: false },
    { name: 'URL_AOS', type: 'text', required: false },
    { name: 'URL_IOS', type: 'text', required: false },
    { name: 'URL_PC', type: 'text', required: false },
    { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' },
    { name: '후지급', type: 'text', required: false },
    { name: '라이브 시작 시간', type: 'text', required: false, defaultValue: '00:00' },
    { name: '라이브 종료 시간', type: 'text', required: false, defaultValue: '24:00' },
    { name: 'adid 타겟팅 모수파일', type: 'text', required: false, placeholder: 'adid 파일 구글 드라이브 링크 입력' },
    { name: '데모타겟1', type: 'select', options: ['모두', '남성', '여성'], required: false },
    { name: '데모타겟2', type: 'text', required: false, placeholder: '연령 (예: 20-39)'},
    { name: '앱 패키지명', type: 'text', required: false },
    { name: '광고주 앱 이름', type: 'text', required: true },
    { name: '문구 - 타이틀', type: 'text', required: true },
    { name: '문구 - 서브', type: 'text', required: true },
    { name: '문구 - 서브1 상단', type: 'text', required: true },
    // ▼▼▼ [수정] '문구 - 서브1 하단' 필드 추가 ▼▼▼
    { name: '문구 - 서브1 하단', type: 'text', required: false },
    // ▲▲▲ [수정] ▲▲▲
    { name: '문구 - 서브2', type: 'textarea', required: true },
    // ▼▼▼ [수정] '목록리워드' 필드 추가 ▼▼▼
    { name: '목록리워드', type: 'text', required: false },
    // ▲▲▲ [수정] ▲▲▲
    { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
  ]
},
   'CPA SUBSCRIBE': {
      // ▼▼▼▼▼ [수정] headerOrder에 자동 생성 필드 3개를 다시 추가하여 메일에 정상 노출되도록 복원 ▼▼▼▼▼
      headerOrder: [ '특이사항 메모장', '태깅', '재참여 타입', '광고주', '브랜드', '액션명', '카테고리', '거래처', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', '집행매체1', '집행매체2', 'OS', '광고 정산 타입', '예산', '단가', '총물량_통합', '총물량_AOS', '총물량_IOS', '일물량_통합', '일물량_AOS', '일물량_IOS', '리워드', '광고 집행 시작', '광고 집행 종료', '광고 참여 시작 후 완료 인정 유효기간 (일단위)', '구독 대상 이름', '이미지 인식에 사용할 식별자', '광고주 계정 식별자1', '광고주 계정 식별자2', '광고주 계정 식별자3', '가이드 메세지', '버튼 메세지', '구독 페이지 랜딩 URL', '이미지 인식 예시 이미지', '2차 액션 팝업 사용', '2차 액션 팝업 이미지 링크', '2차 액션 팝업 타이틀', '2차 액션 팝업 액션 버튼명', '2차 액션 팝업 랜딩 URL', 'URL', '소재', '라이브 시작 시간', '라이브 종료 시간', 'adid 타겟팅 모수파일', '데모타겟1', '데모타겟2', '광고주 앱 이름', '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '문구 - 서브2', '노출 대상' ],
      // ▲▲▲▲▲ [수정] ▲▲▲▲▲
      fields: [ // fields 배열에서는 자동 생성 필드들이 빠져있어 UI에는 노출되지 않습니다.
        { name: '특이사항 메모장', type: 'textarea', required: false },
        { name: '태깅', type: 'select', options: ['네이버뉴스','네이버포스트','라방시청','라방알림','바이럴','블로그','스토어알림','유튜브','인스타','카카오채널','페이스북','틱톡','트위터', '참여형'], required: true },
        { name: '재참여 타입', type: 'select', options: ['단일', '일일 한번', '무한'], required: true },
        { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
        { name: '브랜드', type: 'text', required: true },
        { name: '액션명', type: 'text', required: true },
        { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
        { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
        { name: '광고주 CS 담당자 이름', type: 'text', required: false },
        { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
        { name: '집행매체1', type: 'select', options: ['쿠키오븐', '애디슨 네트워크', '네이버페이'], required: true },
        { name: '집행매체2_쿠키오븐', label: '집행매체2', type: 'select', options: ['전체', '웹툰', '시리즈'], required: true, dependency: { field: '집행매체1', showsOn: '쿠키오븐' } },
        { name: '집행매체2_애디슨', label: '집행매체2', type: 'select', options: ['전체', '특정 매체만 진행'], required: true, dependency: { field: '집행매체1', showsOn: '애디슨 네트워크' } },
        { name: '집행매체2_애디슨_특정', label: '특정 매체명', type: 'text', placeholder: '특정 매체명 입력', required: true, dependency: { field: '집행매체2_애디슨', showsOn: '특정 매체만 진행' } },
        { name: 'OS_DROPDOWN', label: 'OS', type: 'select', options: ['전체', 'AOS', 'IOS'], required: true, dependency: { field: '집행매체1', showsOn: ['쿠키오븐', '애디슨 네트워크'] } },
        { name: 'OS_CHECKBOX', label: 'OS', type: 'checkbox', options: ['AOS', 'IOS', 'AOS+IOS', 'PC'], required: true, dependency: { field: '집행매체1', showsOn: '네이버페이' } },
        { name: '광고 정산 타입', type: 'select', options: ['CPI', 'CPE', 'CPA_SNS', 'CPA_사전예약', 'CPA_회원가입', 'CPA_금융', 'CPQ', 'CPS', 'CPC', '기타'], required: true },
        { name: '예산', type: 'number-unlimited', required: true },
        { name: '단가', type: 'number', required: true },
        { name: '총물량', type: 'volume_split', required: true },
        { name: '일물량', type: 'volume_split', required: true },
        { name: '리워드', type: 'text', required: true, placeholder: '매체와 단가 입력 시 자동 계산', dependency: { field: '집행매체1', hidesOn: ['애디슨 네트워크'] } },
        { name: '광고 집행 시작', type: 'datetime-local', required: true },
        { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
        { name: '광고 참여 시작 후 완료 인정 유효기간 (일단위)', type: 'text', required: false, defaultValue: '1'  },
        { name: '구독 대상 이름', type: 'select', options: ['기본이벤트','유튜브 구독(채널메인)','유튜브 구독(특정영상)','언론사 구독','팔로우','좋아요','채널추가','네이버TV 구독','스토어찜','쇼핑라이브 알림받기','라이브방송 참여하기','유튜브_좋아요','네이버_플레이스_저장', '틱톡', 'X(트위터)'], required: true },
        { name: '이미지 인식에 사용할 식별자', type: 'text', required: true, dependency: { field: '구독 대상 이름', hidesOn: ['유튜브 구독(채널메인)', '유튜브 구독(특정영상)', '팔로우', '좋아요', '채널추가', '유튜브_좋아요', '언론사 구독', '틱톡', 'X(트위터)'] } },
        { name: '광고주 계정 식별자1', type: 'text', required: true, dependency: { field: '구독 대상 이름', showsOn: ['유튜브 구독(채널메인)', '유튜브 구독(특정영상)', '팔로우', '좋아요', '채널추가', '유튜브_좋아요', '언론사 구독', '틱톡', 'X(트위터)'] } },
        { name: '광고주 계정 식별자2', type: 'text', required: false, dependency: { field: '구독 대상 이름', showsOn: ['유튜브 구독(채널메인)', '유튜브 구독(특정영상)', '팔로우', '좋아요', '채널추가', '유튜브_좋아요', '언론사 구독', '틱톡', 'X(트위터)'] } },
        { name: '광고주 계정 식별자3', type: 'text', required: false, dependency: { field: '구독 대상 이름', showsOn: ['유튜브 구독(채널메인)', '유튜브 구독(특정영상)', '팔로우', '좋아요', '채널추가', '유튜브_좋아요', '언론사 구독', '틱톡', 'X(트위터)'] } },
        { name: '구독 페이지 랜딩 URL', type: 'text', required: true, placeholder: '인스타그램 사용자 ID만 입력', dependency: { field: '구독 대상 이름', showsOn: '팔로우' } },
        { name: '이미지 인식 예시 이미지', type: 'text', required: false },
        { name: '2차 액션 팝업 사용', type: 'group_checkbox', label: '2차 액션 팝업 사용' },
        { name: '2차 액션 팝업 이미지 링크', type: 'text', required: true, dependency: { field: '2차 액션 팝업 사용', showsOn: true } },
        { name: '2차 액션 팝업 타이틀', type: 'text', required: true, dependency: { field: '2차 액션 팝업 사용', showsOn: true } },
        { name: '2차 액션 팝업 액션 버튼명', type: 'text', required: true, dependency: { field: '2차 액션 팝업 사용', showsOn: true } },
        { name: '2차 액션 팝업 랜딩 URL', type: 'text', required: true, dependency: { field: '2차 액션 팝업 사용', showsOn: true } },
        { name: 'URL', type: 'text', required: true, dependency: { field: '구독 대상 이름', hidesOn: '팔로우' } },
        { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' },
        { name: '라이브 시작 시간', type: 'text', required: false, defaultValue: '00:00' },
        { name: '라이브 종료 시간', type: 'text', required: false, defaultValue: '24:00' },
        { name: 'adid 타겟팅 모수파일', type: 'text', required: false, placeholder: 'adid 파일 구글 드라이브 링크 입력' },
        { name: '데모타겟1', type: 'select', options: ['모두', '남성', '여성'], required: false },
        { name: '데모타겟2', type: 'text', required: false, placeholder: '연령 (예: 20-39)'},
        { name: '광고주 앱 이름', type: 'text', required: false },
        { name: '문구 - 타이틀', type: 'text', required: true },
        { name: '문구 - 서브', type: 'text', required: true },
        { name: '문구 - 서브1 상단', type: 'text', required: true },
        { name: '문구 - 서브2', type: 'textarea', required: true },
        { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
      ]
    },
      'CPC': {
  headerOrder: [ '특이사항 메모장', '태깅', '재참여 타입', '광고주', '브랜드', '액션명', '카테고리', '거래처', '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', '집행매체1', '집행매체2', 'OS', '광고 정산 타입', '예산', '단가', '총물량_통합', '총물량_AOS', '총물량_IOS', '일물량_통합', '일물량_AOS', '일물량_IOS', '리워드', '광고 집행 시작', '광고 집행 종료', '광고 참여 시작 후 완료 인정 유효기간 (일단위)', 'URL_기본', 'URL_AOS', 'URL_IOS', 'URL_PC', '상세 자동참여 여부', '상세 랜딩 전용 URL', '노출 유지 여부', '광고상세 링크 통한 직접 진입 미허용', '(메타) 클릭 리워드 지급 금액', '(메타) 클릭 리워드 종료 일자', '소재', '후지급', '라이브 시작 시간', '라이브 종료 시간', 'adid 타겟팅 모수파일', '데모타겟1', '데모타겟2', '앱 패키지명', '광고주 앱 이름', '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '문구 - 서브2', '노출 대상' ],
  fields: [
    { name: '특이사항 메모장', type: 'textarea', required: false },
    { name: '태깅', type: 'text', defaultValue: 'CPC', readonly: true, required: true },
    { name: '재참여 타입', type: 'select', options: ['단일', '일일 한번', '무한'], required: true },
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: '브랜드', type: 'text', required: true },
    { name: '액션명', type: 'text', required: true },
    { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
    { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
    { name: '리포트 타입', type: 'select', options: ['일반', 'CPP', 'CPS', 'CPQ', 'CPC', 'CPM', 'CPS-RewardFail'], required: true },
    { name: '광고주 CS 담당자 이름', type: 'text', required: false },
    { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
    { name: '집행매체1', type: 'select', options: ['쿠키오븐', '애디슨 네트워크', '네이버페이'], required: true },
    { name: '집행매체2_쿠키오븐', label: '집행매체2', type: 'select', options: ['전체', '웹툰', '시리즈'], required: true, dependency: { field: '집행매체1', showsOn: '쿠키오븐' } },
    { name: '집행매체2_애디슨', label: '집행매체2', type: 'select', options: ['전체', '특정 매체만 진행'], required: true, dependency: { field: '집행매체1', showsOn: '애디슨 네트워크' } },
    { name: '집행매체2_애디슨_특정', label: '특정 매체명', type: 'text', placeholder: '특정 매체명 입력', required: true, dependency: { field: '집행매체2_애디슨', showsOn: '특정 매체만 진행' } },
    { name: 'OS_DROPDOWN', label: 'OS', type: 'select', options: ['전체', 'AOS', 'IOS'], required: true, dependency: { field: '집행매체1', showsOn: ['쿠키오븐', '애디슨 네트워크'] } },
    { name: 'OS_CHECKBOX', label: 'OS', type: 'checkbox', options: ['AOS', 'IOS', 'AOS+IOS', 'PC'], required: true, dependency: { field: '집행매체1', showsOn: '네이버페이' } },
    { name: '광고 정산 타입', type: 'select', options: ['CPI', 'CPE', 'CPA_SNS', 'CPA_사전예약', 'CPA_회원가입', 'CPA_금융', 'CPQ', 'CPS', 'CPC', '기타'], defaultValue: 'CPC', required: true },
    { name: '예산', type: 'number-unlimited', required: true },
    { name: '단가', type: 'number', required: true },
    { name: '총물량', type: 'volume_split', required: true },
    { name: '일물량', type: 'volume_split', required: true },
    { name: '리워드', type: 'text', required: true, placeholder: '매체와 단가 입력 시 자동 계산', dependency: { field: '집행매체1', hidesOn: ['애디슨 네트워크'] } },
    { name: '광고 집행 시작', type: 'datetime-local', required: true },
    { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '광고 참여 시작 후 완료 인정 유효기간 (일단위)', type: 'text', required: false, defaultValue: '1'  },
    { name: 'URL_기본', type: 'text', required: false },
    { name: 'URL_AOS', type: 'text', required: false },
    { name: 'URL_IOS', type: 'text', required: false },
    { name: 'URL_PC', type: 'text', required: false },
    { name: '상세 자동참여 여부', type: 'group_checkbox', label: '상세 자동참여 여부', defaultValue: true, required: false, dependency: { field: '집행매체1', showsOn: '네이버페이' } },
    { name: '상세 랜딩 전용 URL', type: 'text', required: true, placeholder: 'URL 입력 시 자동 기입, 수정 가능', dependency: { field: '집행매체1', showsOn: '네이버페이' } },
    { name: '노출 유지 여부', type: 'group_checkbox', label: '노출 유지 여부', defaultValue: false, required: false, dependency: { field: '집행매체1', showsOn: '네이버페이' } },
    { name: '광고상세 링크 통한 직접 진입 미허용', type: 'group_checkbox', label: '광고상세 링크 통한 직접 진입 미허용', defaultValue: true, required: false, dependency: { field: '집행매체1', showsOn: '네이버페이' } },
    { name: '(메타) 클릭 리워드 지급 금액', type: 'checkbox-text-hybrid', label: '(메타) 클릭 리워드 지급 금액', copyFrom: '리워드', required: false, dependency: { field: '집행매체1', showsOn: '네이버페이' } },
    { name: '(메타) 클릭 리워드 종료 일자', type: 'checkbox-text-hybrid', label: '(메타) 클릭 리워드 종료 일자', subfieldDefault: '2100-12-31', required: false, dependency: { field: '집행매체1', showsOn: '네이버페이' } },
    { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' },
    { name: '후지급', type: 'text', required: false },
    { name: '라이브 시작 시간', type: 'text', required: false, defaultValue: '00:00' },
    { name: '라이브 종료 시간', type: 'text', required: false, defaultValue: '24:00' },
    { name: 'adid 타겟팅 모수파일', type: 'text', required: false, placeholder: 'adid 파일 구글 드라이브 링크 입력' },
    { name: '데모타겟1', type: 'select', options: ['모두', '남성', '여성'], required: false },
    { name: '데모타겟2', type: 'text', required: false, placeholder: '연령 (예: 20-39)'},
    { name: '앱 패키지명', type: 'text', required: false },
    { name: '광고주 앱 이름', type: 'text', required: false },
    { name: '문구 - 타이틀', type: 'text', required: true },
    { name: '문구 - 서브', type: 'text', required: true },
    { name: '문구 - 서브1 상단', type: 'text', required: true },
    { name: '문구 - 서브2', type: 'textarea', required: true },
    { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
  ]
},
   'CPA COUPON': {
  headerOrder: [ '특이사항 메모장', '태깅', '형식', '광고주', '브랜드', '액션명', '카테고리', '거래처', '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', '광고주 연동 토큰 값', '집행매체1', 'OS', '광고 정산 타입', '예산', '단가', '리워드', '광고 집행 시작', '광고 집행 종료', '광고 노출 중단 시작일시', '광고 노출 중단 종료일시', 'URL_기본', 'URL_AOS', 'URL_IOS', 'URL_PC', '소재', 'adid 타겟팅 모수파일', '광고주 앱 이름', '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '문구 - 서브1 하단', '문구 - 서브2', '노출 대상' ],
  fields: [
    { name: '특이사항 메모장', type: 'textarea', required: false },
    { name: '태깅', type: 'text', defaultValue: '쿠폰형', readonly: true, required: true },
    { name: '형식', type: 'select', options: ['일반형', '발급용', '인보이스용'], required: true },
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: '브랜드', type: 'text', required: true },
    { name: '액션명', type: 'text', required: true },
    { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
    { name: '영업 담당자', type: 'select', options: ['네이버페이_비연동_NBT 쿠폰형', '엔비티 영업실', '네이버페이', '네이버페이_비연동_NF 쿠폰'], defaultValue: '네이버페이_비연동_NBT 쿠폰형', required: true },
    { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
    { name: '리포트 타입', type: 'select', options: ['일반', 'CPP', 'CPS', 'CPQ', 'CPC', 'CPM', 'CPS-RewardFail'], required: true },
    { name: '광고주 CS 담당자 이름', type: 'text', required: false },
    { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
    { name: '광고주 연동 토큰 값', type: 'text', required: true },
    { name: '집행매체1', type: 'text', defaultValue: '네이버페이', readonly: true, required: true },
    { name: 'OS', type: 'checkbox', options: ['AOS', 'IOS', 'AOS+IOS', 'PC'], required: true },
    { name: '광고 정산 타입', type: 'select', options: ['CPI', 'CPE', 'CPA_SNS', 'CPA_사전예약', 'CPA_회원가입', 'CPA_금융', 'CPQ', 'CPS', 'CPC', '기타'], required: true },
    { name: '예산', type: 'number-unlimited', required: true },
    { name: '단가', type: 'number', required: true },
    { name: '리워드', type: 'text', required: true, placeholder: '단가 입력 시 자동 계산' },
    { name: '광고 집행 시작', type: 'datetime-local', required: true },
    { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '광고 노출 중단 시작일시', type: 'datetime-local', required: false },
     { name: '광고 노출 중단 종료일시', type: 'datetime-local-unlimited', required: false },
    { name: 'URL_기본', type: 'text', required: false },
    { name: 'URL_AOS', type: 'text', required: false },
    { name: 'URL_IOS', type: 'text', required: false },
    { name: 'URL_PC', type: 'text', required: false },
    { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' },
    { name: 'adid 타겟팅 모수파일', type: 'text', required: false, placeholder: 'adid 파일 구글 드라이브 링크 입력' },
    { name: '광고주 앱 이름', type: 'text', required: false },
    { name: '문구 - 타이틀', type: 'text', required: true },
    { name: '문구 - 서브', type: 'text', required: true },
    { name: '문구 - 서브1 상단', 'type': 'text', required: true },
    { name: '문구 - 서브1 하단', type: 'text', required: false },
    { name: '문구 - 서브2', type: 'textarea', required: true },
    { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
  ]
},
    '애드네트워크 연동형': {
 headerOrder: ['특이사항 메모장', '애드네트워크 연동형 - 광고 타입', '태깅', '재참여 타입', '광고주', '브랜드', '액션명', '카테고리', '거래처', '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', '광고주 연동 토큰 값', '집행매체1', '집행매체2', 'OS', '광고 정산 타입', '광고 액션 타입', '예산', '단가', '총물량_통합', '총물량_AOS', '총물량_IOS', '일물량_통합', '일물량_AOS', '일물량_IOS', '리워드', '광고 집행 시작', '광고 집행 종료', '광고 참여 시작 후 완료 인정 유효기간 (일단위)', '광고 네트워크 연동 매체', '매체키_기본', '매체키_AOS', '매체키_IOS', '매체키_PC', '소재', '후지급', '라이브 시작 시간', '라이브 종료 시간', 'adid 타겟팅 모수파일', '데모타겟1', '데모타겟2', '앱 패키지명', '광고주 앱 이름', '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '문구 - 서브2', '노출 대상'],
  fields: [
    { name: '특이사항 메모장', type: 'textarea', required: false },
    { name: '애드네트워크 연동형 - 광고 타입', type: 'select', options: ['CPI', 'CPA S2S'], required: true },
    { name: '태깅', type: 'select', options: taggingOptions, required: true },
    { name: '재참여 타입', type: 'select', options: ['단일', '일일 한번', '무한'], required: true },
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: '브랜드', type: 'text', required: true },
    { name: '액션명', type: 'text', required: true },
    { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
    { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
    { name: '리포트 타입', type: 'select', options: ['일반', 'CPP', 'CPS', 'CPQ', 'CPC', 'CPM', 'CPS-RewardFail'], required: true },
    { name: '광고주 CS 담당자 이름', type: 'text', required: false },
    { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
    { name: '광고주 연동 토큰 값', type: 'text', required: true },
    { name: '집행매체1', type: 'select', options: ['쿠키오븐', '애디슨 네트워크', '네이버페이'], required: true },
    { name: '집행매체2_쿠키오븐', label: '집행매체2', type: 'select', options: ['전체', '웹툰', '시리즈'], required: true, dependency: { field: '집행매체1', showsOn: '쿠키오븐' } },
    { name: '집행매체2_애디슨', label: '집행매체2', type: 'select', options: ['전체', '특정 매체만 진행'], required: true, dependency: { field: '집행매체1', showsOn: '애디슨 네트워크' } },
    { name: '집행매체2_애디슨_특정', label: '특정 매체명', type: 'text', placeholder: '특정 매체명 입력', required: true, dependency: { field: '집행매체2_애디슨', showsOn: '특정 매체만 진행' } },
    { name: 'OS_DROPDOWN', label: 'OS', type: 'select', options: ['전체', 'AOS', 'IOS'], required: true, dependency: { field: '집행매체1', showsOn: ['쿠키오븐', '애디슨 네트워크'] } },
    { name: 'OS_CHECKBOX', label: 'OS', type: 'checkbox', options: ['AOS', 'IOS', 'AOS+IOS', 'PC'], required: true, dependency: { field: '집행매체1', showsOn: '네이버페이' } },
    { name: '광고 정산 타입', type: 'select', options: ['CPI', 'CPE', 'CPA_SNS', 'CPA_사전예약', 'CPA_회원가입', 'CPA_금융', 'CPQ', 'CPS', 'CPC', '기타'], required: true },
       { name: '광고 액션 타입', type: 'select', options: ['APP', 'WEB'], required: true },

    { name: '예산', type: 'number-unlimited', required: true },
    { name: '단가', type: 'number', required: true },
    { name: '총물량', type: 'volume_split', required: true },
    { name: '일물량', type: 'volume_split', required: true },
    { name: '리워드', type: 'text', required: true, placeholder: '매체와 단가 입력 시 자동 계산', dependency: { field: '집행매체1', hidesOn: ['애디슨 네트워크'] } },
    { name: '광고 집행 시작', type: 'datetime-local', required: true },
    { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '광고 참여 시작 후 완료 인정 유효기간 (일단위)', type: 'text', required: false, defaultValue: '7' },
    { name: '광고 네트워크 연동 매체', type: 'select', options: ['TNK', 'AD POPCORN', 'PINCRUX', 'SUCOMM', 'OHC', 'IVE', 'BUZZVIL', 'ADISON DSP', '나스미디어NAP', 'CAULY', 'GreenP'], required: true },
    { name: '매체키', type: 'media_key_split', required: true },
    { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' },
    { name: '후지급', type: 'text', required: false },
    { name: '라이브 시작 시간', type: 'text', required: false, defaultValue: '00:00' },
    { name: '라이브 종료 시간', type: 'text', required: false, defaultValue: '24:00' },
    { name: 'adid 타겟팅 모수파일', type: 'text', required: false, placeholder: 'adid 파일 구글 드라이브 링크 입력' },
    { name: '데모타겟1', type: 'select', options: ['모두', '남성', '여성'], required: false },
    { name: '데모타겟2', type: 'text', required: false, placeholder: '연령 (예: 20-39)' },
    { name: '앱 패키지명', type: 'text', required: false },
    { name: '광고주 앱 이름', type: 'text', required: false },
    { name: '문구 - 타이틀', type: 'text', required: true },
    { name: '문구 - 서브', type: 'text', required: true },
    { name: '문구 - 서브1 상단', type: 'text', required: true },
    { name: '문구 - 서브2', type: 'textarea', required: true },
    { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
  ]
},
    '네이버페이 알림받기': {
  headerOrder: [ '특이사항 메모장', '태깅', '재참여 타입', '광고주', '브랜드', '액션명', '카테고리', '거래처', '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', '광고주 연동 토큰 값', '집행매체1', 'OS', '광고 정산 타입', '예산', '단가', '총물량', '일물량', '리워드', '광고 집행 시작', '광고 집행 종료', 'URL', '광고 타입', '소재', '이벤트 상세안내 이미지 경로', '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '문구 - 서브1 하단', '액션 버튼', '문구 - 서브2', '(메타) NF 광고주 연동 타입', '(메타) NF 광고주 연동 ID', '노출 대상' ],
  fields: [
    { name: '특이사항 메모장', type: 'textarea', required: false },
    { name: '태깅', type: 'select', options: ['스토어알림', '라방알림'], required: true },
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: '브랜드', type: 'text', required: true },
    { name: '액션명', type: 'select', options: ['브랜드스토어', '스마트스토어', '라이브 방송'], required: true },
    { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
    { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
    { name: '광고주 CS 담당자 이름', type: 'text', required: false },
    { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
    { name: '집행매체1', type: 'text', defaultValue: '네이버페이', readonly: true, required: true },
    { name: 'OS', type: 'checkbox', options: ['AOS', 'IOS', 'AOS+IOS', 'PC'], required: true },
    { name: '예산', type: 'number-unlimited', required: true },
    { name: '단가', type: 'number', defaultValue: '400', required: true },
    { name: '총물량', type: 'number-unlimited', required: true },
    { name: '일물량', type: 'text', required: true },
    { name: '리워드', type: 'text', defaultValue: '100', required: true },
    { name: '광고 집행 시작', type: 'datetime-local', required: true },
    { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: 'URL', type: 'text', required: true },
    { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' },
    { name: '문구 - 타이틀', type: 'text', required: true },
    { name: '문구 - 서브', type: 'text', defaultValue: '알림받기 추가하면', required: true },
    { name: '문구 - 서브1 상단', type: 'text', required: true },
    { name: '문구 - 서브1 하단', type: 'text', defaultValue: '즉시적립!(단, 25시간 내 알림해제 시 포인트 회수)', readonly: true, required: true },
    { name: '액션 버튼', type: 'text', defaultValue: '참여하고 100포인트 받기', readonly: true, required: true },
    { name: '문구 - 서브2', type: 'textarea', defaultValue: '* 25시간 내 알림 설정을 해제하는 경우 적립된 포인트가 회수됩니다.\n* 참여 버튼을 눌러 이동한 페이지를 이탈하지 않고 바로 알림설정을 해야 정확한 포인트가 적립됩니다.\n* 이미 알림받기를 설정해 두었다면 참여 대상이 아닙니다.\n* 최초 1회만 참여 가능합니다.\n* 본 이벤트는 선착순 조기 종료될 수 있습니다.', readonly: true, required: true },
    { name: '(메타) NF 광고주 연동 타입', type: 'text', readonly: true, required: true },
    { name: '(메타) NF 광고주 연동 ID', type: 'text', required: true },
    { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
  ]
},
   '쿠키오븐 스마트스토어 CPS': {
   headerOrder: [ 
    '특이사항 메모장', '태깅', '재참여 타입', '광고주', '브랜드', '액션명', 
    '카테고리', '거래처', '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', 
    '정산 타입 Block 처리 설정(부정 결제 취소 유저 대상)', '광고 상세 타입', '광고주 연동 토큰 값', 
    '집행매체1', '집행매체2', 'OS', '광고 정산 타입', '예산', '전체 목록 노출 여부', 
    '단가', '총물량', '일물량', '리워드', '광고 집행 시작', '광고 집행 종료', 
    '광고 노출 중단 시작일시', '광고 노출 중단 종료일시', '최소 결제 금액', '파트너 광고주 타입', 
    '파트너 광고주 ID', '참여 경로 유형(app/web)', 'URL', '소재', '문구 - 타이틀', '문구 - 서브', 
    '문구 - 서브1 상단', '문구 - 서브1 하단', '문구 - 서브2', '노출 대상' // ▼▼▼ [수정] '문구 - 서브1 하단' 추가 ▼▼▼
  ],
  fields: [
    { name: '특이사항 메모장', type: 'textarea', required: false },
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: '브랜드', type: 'text', required: true },
     { name: '액션명', type: 'number', step: 'any', required: true, placeholder: '숫자만 입력 (예: 2.5)' },
    { name: '카테고리', type: 'select', options: newCategoryOptions, required: true }, 
    { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
    { name: '광고주 CS 담당자 이름', type: 'text', required: false, defaultValue: '쿠키오븐(노션)' },
    { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
    { name: '광고 상세 타입', type: 'select', options: ['도착보장 상품 구매','특정 판매자 상품 구매','도착보장 내 특정 판매자 상품 구매','특정 판매자 특정 상품 구매'], required: true },
    { name: '집행매체1', type: 'text', defaultValue: '쿠키오븐', readonly: true, required: true },
    { name: '집행매체2', type: 'select', options: ['전체', '웹툰', '시리즈'], required: true },
    { name: 'OS', type: 'select', options: ['전체', 'AOS', 'iOS'], required: true },
    { name: '예산', type: 'number-unlimited', required: true },
    { name: '단가', type: 'number', required: true },
    { name: '총물량', type: 'number-unlimited', required: true },
    { name: '일물량', type: 'text', required: true },
    { name: '리워드', type: 'text', required: true, placeholder: '단가 입력 시 자동 계산' },
    { name: '광고 집행 시작', type: 'datetime-local', required: true },
    { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '광고 노출 중단 시작일시', type: 'datetime-local', required: false },
     { name: '광고 노출 중단 종료일시', type: 'datetime-local-unlimited', required: false },
    { name: '최소 결제 금액', type: 'text', required: true, readonly: true, placeholder: '액션명 입력 시 자동 계산' },
    { name: '파트너 광고주 ID', type: 'text', required: true },
    { name: '참여 경로 유형(app/web)', type: 'select', options: ['미설정(none)', '앱(app)', '웹(web)'], defaultValue: '미설정(none)', required: true },
    { name: 'URL', type: 'text', required: true },
    { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' },
    { name: '문구 - 타이틀', type: 'text', required: true },
    { name: '문구 - 서브', type: 'text', required: true },
    { name: '문구 - 서브1 상단', type: 'text', required: true },
      { name: '문구 - 서브1 하단', type: 'text', required: false },
    { name: '문구 - 서브2', type: 'textarea', required: true },
    { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
  ]
},

'완전 정률 - 쿠키오븐 스마트스토어 CPS': {
      headerOrder: [
        '특이사항 메모장', '태깅', '재참여 타입', '광고주', '브랜드', '액션명', // 액션명은 메일용 헤더에는 포함
        '카테고리', '거래처', '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일',
        '정산 타입 Block 처리 설정(부정 결제 취소 유저 대상)', '광고 상세 타입', '광고주 연동 토큰 값',
        '집행매체1', '집행매체2', 'OS', '광고 정산 타입', '예산', '일예산_통합', '전체 목록 노출 여부',
        '광고비 R/S율', // 단가 대신 추가
        '총물량', '일물량', '광고 집행 시작', '광고 집행 종료',
        '광고 노출 중단 시작일시', '광고 노출 중단 종료일시', '최소 결제 금액', '최대 인정 결정 금액', // 최대 금액 추가
        '파트너 광고주 타입',
        '파트너 광고주 ID', '참여 경로 유형(app/web)', 'URL', '소재', '문구 - 타이틀', '문구 - 서브',
        '문구 - 서브1 상단', '문구 - 서브1 하단', '문구 - 서브2', '상세 안내', '노출 대상'
      ],
      fields: [
        { name: '특이사항 메모장', type: 'textarea', required: false },
        // 액션명은 fields 에서는 제외
        { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
        { name: '브랜드', type: 'text', required: true },
        { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
        { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
        { name: '광고주 CS 담당자 이름', type: 'text', required: false, defaultValue: '쿠키오븐(노션)' },
        { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
        { name: '광고 상세 타입', type: 'select', options: ['도착보장 상품 구매','특정 판매자 상품 구매','도착보장 내 특정 판매자 상품 구매','특정 판매자 특정 상품 구매'], required: true },
        { name: '집행매체1', type: 'text', defaultValue: '쿠키오븐', readonly: true, required: true },
        { name: '집행매체2', type: 'select', options: ['전체', '웹툰', '시리즈'], required: true },
        { name: 'OS', type: 'select', options: ['전체', 'AOS', 'iOS'], required: true },
        { name: '예산', type: 'number-unlimited', required: true },
        { name: '일예산_통합', label: '일예산', type: 'text-unlimited', required: true },

        { // 단가 대신 추가
          name: '광고비 R/S율', type: 'number', required: true,
          description: '입력값 % (어드민 : 0.입력값) - 예시: 15 입력 -> 15 % (어드민 : 0.15)'
        },
        { name: '총물량', type: 'number-unlimited', required: true },
        { name: '일물량', type: 'text', required: true },
        // 리워드 항목 삭제
        { name: '광고 집행 시작', type: 'datetime-local', required: true },
        { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
        { name: '광고 노출 중단 시작일시', type: 'datetime-local', required: false },
        { name: '광고 노출 중단 종료일시', type: 'datetime-local-unlimited', required: false },
        { name: '최소 결제 금액', type: 'number', required: true, placeholder: '숫자만 입력 (예: 10000)' },
        { name: '최대 인정 결정 금액', type: 'number', required: true, placeholder: '숫자만 입력 (예: 50000)' }, // 최대 금액 추가
        { name: '파트너 광고주 ID', type: 'text', required: true },
        { name: '참여 경로 유형(app/web)', type: 'select', options: ['미설정(none)', '앱(app)', '웹(web)'], defaultValue: '미설정(none)', required: true },
        { name: 'URL', type: 'text', required: true },
        { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' },
        { name: '문구 - 타이틀', type: 'text', required: true },
        { name: '문구 - 서브', type: 'text', required: true },
        { name: '문구 - 서브1 상단', type: 'text', required: true },
        { name: '문구 - 서브1 하단', type: 'text', required: false },
        { name: '문구 - 서브2', type: 'textarea', required: true, placeholder: '광고비 R/S율, 최소/최대 금액 입력 시 자동 계산됩니다.' }, // 자동 계산되므로 readonly 추가
        { name: '상세 안내', type: 'textarea', required: true, rows: 12, defaultValue: detailInfoDefault },
        { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
        // 자동 생성되는 필드 (FormFields.gs 에는 없지만 Registration.gs 에서는 사용)
        // 태깅, 재참여 타입, 리포트 타입, 정산 타입 Block 처리, 광고주 연동 토큰 값, 광고 정산 타입, 전체 목록 노출 여부, 파트너 광고주 타입
      ]
    },

'네이버페이 스마트스토어 CPS': {
  headerOrder: [
    '특이사항 메모장', '태깅', '재참여 타입', '광고주', '브랜드', '액션명', '카테고리', '거래처', '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일',
    '정산 타입 Block 처리 설정(부정 결제 취소 유저 대상)', '광고주 연동 토큰 값', '집행매체1', '광고 정산 타입', '예산', '전체 목록 노출 여부', '단가', '총물량', '일물량', '리워드',
    '광고 집행 시작', '광고 집행 종료', '광고 노출 중단 시작일시', '광고 노출 중단 종료일시', '최소 결제 금액', 'URL', '탭', '소재', '소재 - 이벤트 안내 이미지',
    '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '문구 - 서브1 하단', '문구 - 서브2', '액션 버튼', '(목록) 리워드 조건 설명', '(목록) 리워드 텍스트',
    '(메타) NF 광고주 연동 타입', '(메타) NF 광고주 연동 ID', '노출 대상', 'placement 세팅 정보',
    // 부스팅 광고 필드들
    '부스팅 CPC 광고 태깅', '부스팅 CPC 광고 재참여 타입', '부스팅 CPC 광고 리포트 타입', '부스팅 CPC 광고 광고주 연동 토큰 값',
    '부스팅 CPC 광고 집행매체1', '부스팅 CPC 광고 광고 정산 타입', '부스팅 CPC 광고 전체 목록 노출 여부', '부스팅 CPC 광고 단가', '부스팅 CPC 광고 리워드',
    '부스팅 CPC 광고 광고 집행 시작', '부스팅 CPC 광고 광고 집행 종료', '부스팅 CPC 광고 광고 노출 중단 시작일시', '부스팅 CPC 광고 광고 노출 중단 종료일시',
    '부스팅 CPC 광고 URL', '부스팅 CPC 광고 상세 랜딩 전용 URL', '부스팅 CPC 광고 탭', '부스팅 CPC 광고 소재', '부스팅 CPC 광고 소재 - 이벤트 안내 이미지',
    '부스팅 CPC 광고 문구 - 타이틀', '부스팅 CPC 광고 문구 - 서브', '부스팅 CPC 광고 문구 - 서브1 상단', '부스팅 CPC 광고 문구 - 서브1 하단', '부스팅 CPC 광고 문구 - 서브2',
    '부스팅 CPC 광고 액션 버튼',
    '부스팅 CPC 광고 (목록) 리워드 조건 설명', '부스팅 CPC 광고 (목록) 리워드 텍스트', '부스팅 CPC 광고 (메타) NF 광고주 연동 ID',
    '부스팅 CPC 광고 placement 세팅 정보 기본', '부스팅 CPC 광고 placement 세팅 정보 옵션_추천 세팅 여부', '부스팅 CPC 광고 placement 세팅 정보 옵션_카테고리'
  ],
  fields: [
    { name: 'heading_cps', type: 'heading', label: '네이버페이 스마트스토어 CPS 광고' },
    { name: '특이사항 메모장', type: 'textarea', required: false },
    { name: '태깅', type: 'select', options: ['일반_브랜드펀딩', '일반_플랫폼펀딩', '쇼핑앱_일반_플랫폼펀딩'], required: true },
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: '브랜드', type: 'text', required: true },
    { name: '액션명', type: 'number', step: 'any', required: true, placeholder: '숫자만 입력 (예: 2.5)' },
    { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
    { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
    { name: '광고주 CS 담당자 이름', type: 'text', required: false, defaultValue: '알림받기와 동일하게 NBT -> 네이버페이로 전달 및 처리' },
    { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
    { name: '예산', type: 'number-unlimited', required: true },
    { name: '단가', type: 'number', required: true },
    { name: '총물량', type: 'number-unlimited', required: true },
    { name: '일물량', type: 'text', required: true },
    { name: '리워드', type: 'text', required: true, placeholder: '단가 입력 시 자동 계산' },
    { name: '광고 집행 시작', type: 'datetime-local', required: true },
    { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '광고 노출 중단 시작일시', type: 'datetime-local', required: false },
    { name: '광고 노출 중단 종료일시', type: 'datetime-local-unlimited', required: false },
    { name: '최소 결제 금액', type: 'text', required: true, readonly: true, placeholder: '액션명 입력 시 자동 계산' },
    { name: 'URL', type: 'text', required: true },
    { name: '소재', type: 'text', required: true },
    { name: '소재 - 이벤트 안내 이미지', type: 'text', required: true, defaultValue: 'G:\\공유 드라이브\\000. 소재저장소\\002. 애디슨 네트워크\\000. 디폴트_상세설명\\011. 네이버페이_스마트스토어_일반상품_CPS_디폴트' },
    { name: '문구 - 타이틀', type: 'text', required: true, placeholder: '브랜드 입력 시 자동 완성' },
    { name: '문구 - 서브', type: 'text', required: true, placeholder: '액션명 입력 시 자동 완성' },
    { name: '문구 - 서브1 상단', type: 'text', required: true, placeholder: '액션명 입력 시 자동 완성' },
    { name: '문구 - 서브1 하단', type: 'text', required: true, placeholder: '광고 집행 종료일 입력 시 자동 완성' },
    { name: '액션 버튼', type: 'text', required: true, defaultValue: '참여하고 {REWARD_STR} 적립' },
    { name: '(목록) 리워드 텍스트', type: 'text', required: true, placeholder: '리워드 계산 시 자동 완성' },
    { name: '(메타) NF 광고주 연동 ID', type: 'text', required: true, placeholder: '태깅 선택 시 자동 완성' },
    { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },

    { name: 'heading_boosting', type: 'heading', label: '부스팅 CPC 광고' },
    { name: '부스팅 CPC 광고 태깅', type: 'select', options: ['부스팅_A', '부스팅_B', '부스팅_C'], required: true },
    { name: '부스팅 CPC 광고 광고 집행 시작', type: 'datetime-local', required: true },
    { name: '부스팅 CPC 광고 광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '부스팅 CPC 광고 광고 노출 중단 시작일시', type: 'datetime-local', required: false },
    { name: '부스팅 CPC 광고 광고 노출 중단 종료일시', type: 'datetime-local-unlimited', required: false },
    { name: '부스팅 CPC 광고 소재', type: 'text', required: true },
    { name: '부스팅 CPC 광고 소재 - 이벤트 안내 이미지', type: 'text', required: true, defaultValue: 'G:\\공유 드라이브\\000. 소재저장소\\002. 애디슨오퍼월\\000. 디폴트_상세설명\\011. 네이버페이_스마트스토어_일반상품_CPS_디폴트' },
    { name: '부스팅 CPC 광고 placement 세팅 정보 옵션_추천 세팅 여부', type: 'select', options: ['세팅 O', '세팅 X'], required: true },
    { name: '부스팅 CPC 광고 placement 세팅 정보 옵션_카테고리', type: 'select', options: ['건강', '식품', '생활', '뷰티', '기타'], required: true },
  ]
},

'네이버페이 CPS구매확정형_금액X': {
  headerOrder: [
    '요청사항 메모장', '태깅', '재참여 타입', '광고주', '브랜드', '카테고리', '영업 담당자', '거래처',
    '리포트 타입', '광고주 CS 담당자 이름', '정산 타입 Block 처리 설정(부정 결제 취소 유저 대상)',
    '적립 허용 광고주 연동 선택', '집행매체1', '광고 정산 타입', '광고비 R/S율', '물량 (총/일)',
    '총예산_통합', '일예산_통합', '광고 집행 시작', '광고 집행 종료', '광고 노출 중단 시작일시', '광고 노출 중단 종료일시',
    '최소 결제 금액', 'URL', '탭', '소재', '소재 - 이벤트 안내 이미지',
    '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '문구 - 서브1 하단', '액션 버튼', '문구 - 서브2',
    '(목록) 리워드 조건 설명', '(목록) 리워드 텍스트', '(메타) NF 광고주 연동 타입', '(메타) NF 광고주 연동 ID',
    '노출 대상', 'placement 세팅 정보',
    // 부스팅 광고 필드들
    '부스팅 CPC 광고 태깅', '부스팅 CPC 광고 재참여 타입', '부스팅 CPC 광고 리포트 타입',
    '부스팅 CPC 광고 적립 허용 광고주 연동 선택', '부스팅 CPC 광고 집행매체1', '부스팅 CPC 광고 광고 정산 타입', // <-- 위치 이동
    '부스팅 CPC 광고 전체 목록 노출 여부', '부스팅 CPC 광고 단가', '부스팅 CPC 광고 리워드',
    '부스팅 CPC 광고 광고 집행 시작', '부스팅 CPC 광고 광고 집행 종료',
    '부스팅 CPC 광고 광고 노출 중단 시작일시', '부스팅 CPC 광고 광고 노출 중단 종료일시',
    '부스팅 CPC 광고 URL', '부스팅 CPC 광고 상세 랜딩 전용 URL', '부스팅 CPC 광고 탭',
    '부스팅 CPC 광고 소재', '부스팅 CPC 광고 소재 - 이벤트 안내 이미지',
    '부스팅 CPC 광고 문구 - 타이틀', '부스팅 CPC 광고 문구 - 서브',
    '부스팅 CPC 광고 문구 - 서브1 상단', '부스팅 CPC 광고 문구 - 서브1 하단', '부스팅 CPC 광고 문구 - 서브2',
    '부스팅 CPC 광고 액션 버튼', '부스팅 CPC 광고 (목록) 리워드 조건 설명', '부스팅 CPC 광고 (목록) 리워드 텍스트',
    '부스팅 CPC 광고 (메타) NF 광고주 연동 ID', // <-- 위치 이동
    '부스팅 CPC 광고 placement 세팅 정보 기본',
    '부스팅 CPC 광고 placement 세팅 정보 옵션_추천 세팅 여부', '부스팅 CPC 광고 placement 세팅 정보 옵션_카테고리'
  ],
  fields: [
    { name: 'heading_cps', type: 'heading', label: '네이버페이 CPS 구매확정형 본광고' },
    { name: '요청사항 메모장', type: 'textarea', required: false },
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: '브랜드', type: 'text', required: true },
    { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
    { name: '영업 담당자', type: 'select', options: ['엔비티 영업실', '네이버페이'], defaultValue: '엔비티 영업실', required: true },
    { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
    
    { name: '광고비 R/S율', type: 'text', required: true, defaultValue: '0.2' },
    { name: '총예산_통합', type: 'text', required: true },
    { name: '일예산_통합', type: 'text', required: true },
    
    { name: '광고 집행 시작', type: 'datetime-local', required: true },
    { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '광고 노출 중단 시작일시', type: 'datetime-local', required: false },
    { name: '광고 노출 중단 종료일시', type: 'datetime-local-unlimited', required: false },
    
    { name: 'URL', type: 'text', required: true },
    // '탭' 제거 (Hidden)
    { name: '소재', type: 'text', required: true },
    { name: '소재 - 이벤트 안내 이미지', type: 'text', required: true, defaultValue: 'G:\\공유 드라이브\\000. 소재저장소\\002. 애디슨오퍼월\\000. 디폴트_상세설명\\012. 네이버페이_구매확정형_CPS_디폴트' },
    
    { name: '문구 - 타이틀', type: 'text', required: true, placeholder: '브랜드 입력 시 자동 완성' },
    { name: '문구 - 서브', type: 'text', required: true, defaultValue: '구매확정 시 즉시 추가적립' },
    { name: '문구 - 서브1 상단', type: 'text', required: true, defaultValue: '결제 이후 구매확정까지 완료하면' },
    { name: '문구 - 서브1 하단', type: 'text', required: true, defaultValue: '매일 선착순 이벤트' },
    { name: '액션 버튼', type: 'text', required: true, defaultValue: '참여하고 10% 적립' },
    { name: '문구 - 서브2', type: 'textarea', required: true, rows: 8, defaultValue: '*본 이벤트는 선착순으로 조기 종료될 수 있어요\n*이벤트 참여하기 클릭 후 24시간 내 "처음 구매금액 조건을 충족하는 결제"와 매칭돼요\n*참여하기 클릭 후 24시간 이내에도 선착순 조기 종료 시에는 적립이 안돼요\n*네이버 쇼핑 이벤트 참여 시 로그인한 네이버 ID로 구매 시에만 포인트가 지급돼요\n*결제 이후 구매확정까지 완료해야 포인트가 지급돼요\n*결제일로부터 60일 이내 구매확정 시에만 포인트가 지급돼요\n*아래 주의사항을 꼭 읽어보세요!' },
    
    // '(목록) 리워드 조건 설명' 제거 (Hidden)
    { name: '(메타) NF 광고주 연동 ID', type: 'text', required: true, description: '입력값 앞에 "store_BRCPS_decided_"가 자동으로 붙습니다.' },
    { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },

    { name: 'heading_boosting', type: 'heading', label: '부스팅 CPC 광고' },
    // 부스팅 관련 Hidden 필드들 제거됨
    
    { name: '부스팅 CPC 광고 광고 집행 시작', type: 'datetime-local', required: true },
    { name: '부스팅 CPC 광고 광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '부스팅 CPC 광고 광고 노출 중단 시작일시', type: 'datetime-local', required: false },
    { name: '부스팅 CPC 광고 광고 노출 중단 종료일시', type: 'datetime-local-unlimited', required: false },
    
    { name: '부스팅 CPC 광고 소재', type: 'text', required: true },
    { name: '부스팅 CPC 광고 소재 - 이벤트 안내 이미지', type: 'text', required: true, defaultValue: 'G:\\공유 드라이브\\000. 소재저장소\\002. 애디슨오퍼월\\000. 디폴트_상세설명\\012. 네이버페이_구매확정형_CPS_디폴트' },
    
    { name: '부스팅 CPC 광고 액션 버튼', type: 'text', required: true, defaultValue: '참여하고 10% 적립' },
    
    { name: '부스팅 CPC 광고 placement 세팅 정보 옵션_추천 세팅 여부', type: 'select', options: ['세팅 O', '세팅 X'], required: true },
    { name: '부스팅 CPC 광고 placement 세팅 정보 옵션_카테고리', type: 'select', options: ['건강', '식품', '생활', '뷰티', '기타'], required: true },
  ]
},

 'CPQ': {
      headerOrder: [
        '특이사항 메모장', '태깅', '재참여 타입', '광고주', '브랜드', '액션명', '카테고리', '거래처', 
        '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', '집행매체1', '집행매체2', 'OS', 
        '광고 정산 타입', '예산', '단가', '총물량', '리워드', '일물량', '광고 집행 시작', '광고 집행 종료', 
        '광고 참여 시작 후 완료 인정 유효기간 (일단위)', '소재', '후지급', '라이브 시작 시간', '라이브 종료 시간', 
        'adid 타겟팅 모수파일', '데모타겟1', '데모타겟2', 'CPQ 뷰', '랜딩 형태', '임배디드 연결 형태', 
        '유튜브 ID / 네이버 TV CODE', '이미지', '이미지 연결 링크', '퀴즈', '정답', '정답 placeholder 텍스트', 
        '오답 alert 메시지', '사전 랜딩(딥링크) 사용', '사전 랜딩 실행 필수', '사전 랜딩 URL', 
        '사전 랜딩 버튼 텍스트', '사전 랜딩 미실행 alert 메시지', '2차 액션 팝업 사용 여부', 
        '2차 액션 팝업 타이틀', '2차 액션 팝업 액션 버튼명', '2차 액션 팝업 랜딩 URL', '2차 액션 팝업 이미지 경로', 
        '앱 패키지명', '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '문구 - 서브2', '노출 대상'
      ],
      fields: [
        { name: '특이사항 메모장', type: 'textarea', required: false },
        { name: '태깅', type: 'text', defaultValue: 'CPQ', readonly: true, required: true },
        { name: '재참여 타입', type: 'select', options: ['단일', '일일 한번', '무한'], required: true },
        { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
        { name: '브랜드', type: 'text', required: true },
        { name: '액션명', type: 'text', required: true },
        { name: '카테고리', type: 'select', options: newCategoryOptions, required: true }, 
        { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
        { name: '리포트 타입', type: 'select', options: ['일반', 'CPP', 'CPS', 'CPQ', 'CPC', 'CPM', 'CPS-RewardFail'], required: true },
        { name: '광고주 CS 담당자 이름', type: 'text', required: false },
        { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
        { name: '집행매체1', type: 'select', options: ['쿠키오븐', '애디슨 네트워크'], required: true },
        { name: '집행매체2_쿠키오븐', label: '집행매체2', type: 'select', options: ['전체', '웹툰', '시리즈'], required: true, dependency: { field: '집행매체1', showsOn: '쿠키오븐' } },
        { name: '집행매체2_애디슨', label: '집행매체2', type: 'select', options: ['전체', '특정 매체만 진행'], required: true, dependency: { field: '집행매체1', showsOn: '애디슨 네트워크' } },
        { name: '집행매체2_애디슨_특정', label: '특정 매체명', type: 'text', placeholder: '특정 매체명 입력', required: true, dependency: { field: '집행매체2_애디슨', showsOn: '특정 매체만 진행' } },
        { name: 'OS', type: 'select', options: ['전체', 'AOS', 'IOS'], required: true },
        { name: '광고 정산 타입', type: 'select', options: ['CPI', 'CPE', 'CPA_SNS', 'CPA_사전예약', 'CPA_회원가입', 'CPA_금융', 'CPQ', 'CPS', 'CPC', '기타'], required: true },
        { name: '예산', type: 'number-unlimited', required: true },
        { name: '단가', type: 'number', required: true },
        { name: '총물량', type: 'number-unlimited', required: true },
        { name: '리워드', type: 'text', required: true, dependency: { field: '집행매체1', showsOn: '쿠키오븐' } },
        { name: '일물량', type: 'textarea', required: true },
        { name: '광고 집행 시작', type: 'datetime-local', required: true },
        { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
        { name: '광고 참여 시작 후 완료 인정 유효기간 (일단위)', type: 'text', required: false, defaultValue: '1'  },
        { name: '소재', type: 'text', required: true },
        { name: '후지급', type: 'text', required: false },
        { name: '라이브 시작 시간', type: 'text', required: false, defaultValue: '00:00' },
        { name: '라이브 종료 시간', type: 'text', required: false, defaultValue: '24:00' },
        { name: 'adid 타겟팅 모수파일', type: 'text', required: false, placeholder: 'adid 파일 구글 드라이브 링크 입력' },
        { name: '데모타겟1', type: 'text', required: false },
        { name: '데모타겟2', type: 'text', required: false },
        { name: 'CPQ 뷰', type: 'select', options: ['offerwall', 'renewal'], defaultValue: 'offerwall', required: true },
        { name: '랜딩 형태', type: 'select', options: ['아웃랜딩(이미지형 CPQ)', '아웃랜딩(CPVQ)', '임베디드(CPVQ)'], required: true },
        { name: '임배디드 연결 형태', type: 'select', options: ['유튜브ID', '네이버 TV CODE'], required: false },
        { name: '유튜브 ID / 네이버 TV CODE', type: 'text', required: false },
        { name: '이미지', type: 'text', required: false },
        { name: '이미지 연결 링크', type: 'text', required: false },
        { name: '퀴즈', type: 'textarea', required: true },
        { name: '정답', type: 'text', required: true },
        { name: '정답 placeholder 텍스트', type: 'text', required: false },
        { name: '오답 alert 메시지', type: 'text', required: false, defaultValue: '오답입니다. 다시 한번 힌트 확인 후 정답을 입력해 주세요!' },
        // ▼▼▼▼▼ [수정] 아래 관련 필드 4개의 이름을 '사전 랜딩(딥링크) 사용'으로 원복합니다 ▼▼▼▼▼
        { name: '사전 랜딩(딥링크) 사용', type: 'select', options: ['TRUE', 'FALSE'], required: true },
        { name: '사전 랜딩 실행 필수', type: 'text', readonly: true, required: false },
        { name: '사전 랜딩 URL', type: 'text', required: false, dependency: { field: '사전 랜딩(딥링크) 사용', showsOn: 'TRUE' } },
        { name: '사전 랜딩 버튼 텍스트', type: 'text', required: false, dependency: { field: '사전 랜딩(딥링크) 사용', showsOn: 'TRUE' } },
        { name: '사전 랜딩 미실행 alert 메시지', type: 'text', required: false, dependency: { field: '사전 랜딩(딥링크) 사용', showsOn: 'TRUE' } },
        // ▲▲▲▲▲ [수정] ▲▲▲▲▲
        { name: '2차 액션 팝업 사용 여부', type: 'select', options: ['미사용', '사용'], required: true, defaultValue: '미사용' },
        { name: '2차 액션 팝업 타이틀', type: 'text', required: false, dependency: { field: '2차 액션 팝업 사용 여부', showsOn: '사용' } },
        { name: '2차 액션 팝업 액션 버튼명', type: 'text', required: false, dependency: { field: '2차 액션 팝업 사용 여부', showsOn: '사용' } },
        { name: '2차 액션 팝업 랜딩 URL', type: 'text', required: false, dependency: { field: '2차 액션 팝업 사용 여부', showsOn: '사용' } },
        { name: '2차 액션 팝업 이미지 경로', type: 'text', required: false, dependency: { field: '2차 액션 팝업 사용 여부', showsOn: '사용' } },
        { name: '앱 패키지명', type: 'text', required: false },
        { name: '문구 - 타이틀', type: 'text', required: true },
        { name: '문구 - 서브', type: 'text', required: true },
        { name: '문구 - 서브1 상단', type: 'text', required: true },
        { name: '문구 - 서브2', type: 'textarea', required: true },
        { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
      ]
    },
    'CPA SUBSCRIBE 후지급': {
      headerOrder: [ '특이사항 메모장', '태깅', '재참여 타입', '광고주', '브랜드', '액션명', '카테고리', '거래처', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일', '집행매체1', '집행매체2', 'OS', '광고 정산 타입', '예산', '단가', '총물량_통합', '총물량_AOS', '총물량_IOS', '일물량_통합', '일물량_AOS', '일물량_IOS', '리워드', '광고 집행 시작', '광고 집행 종료', '광고 참여 시작 후 완료 인정 유효기간 (일단위)', '구독 대상 이름', '이미지 인식에 사용할 식별자', '광고주 계정 식별자1', '광고주 계정 식별자2', '광고주 계정 식별자3', '가이드 메세지', '버튼 메세지', '구독 페이지 랜딩 URL', '이미지 인식 예시 이미지', '2차 액션 팝업 사용', '2차 액션 팝업 이미지 링크', '2차 액션 팝업 타이틀', '2차 액션 팝업 액션 버튼명', '2차 액션 팝업 랜딩 URL', 'URL', '소재', '후지급', '라이브 시작 시간', '라이브 종료 시간', 
      'adid 타겟팅 모수파일', '데모타겟1', '데모타겟2',
      '문구 - 타이틀', '문구 - 서브', '문구 - 서브1 상단', '액션 버튼', '문구 - 서브2', '노출 대상' ],

      fields: [ 
        { name: '특이사항 메모장', type: 'textarea', required: false },
        { name: '태깅', type: 'select', options: ['네이버뉴스','네이버포스트','라방시청','라방알림','바이럴','블로그','스토어알림','유튜브','인스타','카카오채널','페이스북','틱톡','트위터', '참여형'], required: true },
        { name: '재참여 타입', type: 'select', options: ['단일', '일일 한번', '무한'], required: true },
        { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
        { name: '브랜드', type: 'text', required: true },
        { name: '액션명', type: 'text', required: true },
        { name: '카테고리', type: 'select', options: newCategoryOptions, required: true },
        { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
        { name: '광고주 CS 담당자 이름', type: 'text', required: false },
        { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
        { name: '집행매체1', type: 'select', options: ['애디슨 네트워크', '네이버페이'], required: true },
        { name: '집행매체2_애디슨', label: '집행매체2', type: 'select', options: ['전체', '특정 매체만 진행'], required: true, dependency: { field: '집행매체1', showsOn: '애디슨 네트워크' } },
        { name: '집행매체2_애디슨_특정', label: '특정 매체명', type: 'text', placeholder: '특정 매체명 입력', required: true, dependency: { field: '집행매체2_애디슨', showsOn: '특정 매체만 진행' } },
        { name: 'OS', type: 'select', options: ['전체', 'AOS', 'IOS'], required: true },
        { name: '광고 정산 타입', type: 'select', options: ['CPI', 'CPE', 'CPA_SNS', 'CPA_사전예약', 'CPA_회원가입', 'CPA_금융', 'CPQ', 'CPS', 'CPC', '기타'], required: true },
        { name: '예산', type: 'number-unlimited', required: true },
        { name: '단가', type: 'number', required: true },
        { name: '총물량', type: 'volume_split', required: true },
        { name: '일물량', type: 'volume_split', required: true },
        { name: '리워드', type: 'text', required: true, placeholder: '매체와 단가 입력 시 자동 계산', dependency: { field: '집행매체1', hidesOn: ['애디슨 네트워크'] } },
        { name: '광고 집행 시작', type: 'datetime-local', required: true },
        { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
        { name: '광고 참여 시작 후 완료 인정 유효기간 (일단위)', type: 'text', required: false, defaultValue: '1'  },
        { name: '구독 대상 이름', type: 'select', options: ['기본이벤트','유튜브 구독(채널메인)','유튜브 구독(특정영상)','언론사 구독','팔로우','좋아요','채널추가','네이버TV 구독','스토어찜','쇼핑라이브 알림받기','라이브방송 참여하기','유튜브_좋아요','네이버_플레이스_저장', '틱톡', 'X(트위터)'], required: true },
        { name: '이미지 인식에 사용할 식별자', type: 'text', required: true, dependency: { field: '구독 대상 이름', hidesOn: ['유튜브 구독(채널메인)', '유튜브 구독(특정영상)', '팔로우', '좋아요', '채널추가', '유튜브_좋아요', '언론사 구독', '틱톡', 'X(트위터)'] } },

        { name: '광고주 계정 식별자1', type: 'text', required: true, dependency: { field: '구독 대상 이름', showsOn: ['유튜브 구독(채널메인)', '유튜브 구독(특정영상)', '팔로우', '좋아요', '채널추가', '유튜브_좋아요', '언론사 구독', '틱톡', 'X(트위터)'] } },
        { name: '광고주 계정 식별자2', type: 'text', required: false, dependency: { field: '구독 대상 이름', showsOn: ['유튜브 구독(채널메인)', '유튜브 구독(특정영상)', '팔로우', '좋아요', '채널추가', '유튜브_좋아요', '언론사 구독', '틱톡', 'X(트위터)'] } },
        { name: '광고주 계정 식별자3', type: 'text', required: false, dependency: { field: '구독 대상 이름', showsOn: ['유튜브 구독(채널메인)', '유튜브 구독(특정영상)', '팔로우', '좋아요', '채널추가', '유튜브_좋아요', '언론사 구독', '틱톡', 'X(트위터)'] } },
        { name: '구독 페이지 랜딩 URL', type: 'text', required: true, placeholder: '인스타그램 사용자 ID만 입력', dependency: { field: '구독 대상 이름', showsOn: '팔로우' } },
        { name: '이미지 인식 예시 이미지', type: 'text', required: false },
        { name: '2차 액션 팝업 사용', type: 'group_checkbox', label: '2차 액션 팝업 사용' },
        { name: '2차 액션 팝업 이미지 링크', type: 'text', required: true, dependency: { field: '2차 액션 팝업 사용', showsOn: true } },
        { name: '2차 액션 팝업 타이틀', type: 'text', required: true, dependency: { field: '2차 액션 팝업 사용', showsOn: true } },
        { name: '2차 액션 팝업 액션 버튼명', type: 'text', required: true, dependency: { field: '2차 액션 팝업 사용', showsOn: true } },
        { name: '2차 액션 팝업 랜딩 URL', type: 'text', required: true, dependency: { field: '2차 액션 팝업 사용', showsOn: true } },
        { name: 'URL', type: 'text', required: true, dependency: { field: '구독 대상 이름', hidesOn: '팔로우' } },
        { name: '소재', type: 'text', required: true, placeholder: '소재 경로 입력' },
        { name: '후지급', type: 'text', required: true, defaultValue: '24' },
        { name: '라이브 시작 시간', type: 'text', required: false, defaultValue: '00:00' },
        { name: '라이브 종료 시간', type: 'text', required: false, defaultValue: '24:00' },
        { name: 'adid 타겟팅 모수파일', type: 'text', required: false, placeholder: 'adid 파일 구글 드라이브 링크 입력' },
        { name: '데모타겟1', type: 'select', options: ['모두', '남성', '여성'], required: false },
        { name: '데모타겟2', type: 'text', required: false, placeholder: '연령 (예: 20-39)'},
        { name: '광고주 앱 이름', type: 'text', required: false },
        { name: '문구 - 타이틀', type: 'text', required: true },
        { name: '문구 - 서브', type: 'text', required: true },
        { name: '문구 - 서브1 상단', type: 'text', required: true },
        { name: '액션 버튼', type: 'text', required: true, defaultValue: '참여하고 24시간 뒤에 {UNIT} 받기' },
        { name: '문구 - 서브2', type: 'textarea', required: true },
        { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
      ]
    },

'네이버페이 입점비': {
  headerOrder: [
    '네이버페이 입점비 본 광고 신규 등록 여부', '본 광고 타입',
    'CPC 입점비 요청사항', 'CPC 입점비 태깅', 'CPC 입점비 재참여 타입', 'CPC 입점비 광고주', 'CPC 입점비 브랜드',
    'CPC 입점비 카테고리', 'CPC 입점비 거래처', 'CPC 입점비 리포트 타입', 'CPC 입점비 광고주 CS 담당자 이름',
    'CPC 입점비 광고주 CS 담당자 이메일', 'CPC 입점비 본 광고 정보', 'CPC 입점비 집행매체1', 'CPC 입점비 OS',
    'CPC 입점비 광고 정산 타입', 'CPC 입점비 단가', 'CPC 입점비 총물량', 'CPC 입점비 리워드', 'CPC 입점비 일물량',
    'CPC 입점비 광고 집행 시작', 'CPC 입점비 광고 집행 종료', 'CPC 입점비 URL & 상세 랜딩 전용 URL',
    'CPC 입점비 상세 자동참여 여부', 'CPC 입점비 노출 유지 여부', 'CPC 입점비 소재', 'CPC 입점비 라이브 시작 시간',
    'CPC 입점비 라이브 종료 시간', 'CPC 입점비 광고주 앱 이름', // <-- [수정] 헤더 순서에 추가
    'CPC 입점비 문구 - 타이틀', 'CPC 입점비 문구 - 서브',
    'CPC 입점비 (메타) 클릭 리워드 지급 금액', 'CPC 입점비 (메타) 클릭 리워드 종료 일자', 'CPC 입점비 placement',
    'CPC 입점비 노출 대상'
  ],
  fields: [
    { name: '네이버페이 입점비 본 광고 신규 등록 여부', type: 'select', options: ['등록 O', '등록 X'], required: true },
    { name: '본 광고 타입', type: 'select', options: ['CPA S2S', 'CPA TRACKER', 'CPA COUPON'], required: true, dependency: { field: '네이버페이 입점비 본 광고 신규 등록 여부', showsOn: '등록 O' } },
    { name: 'heading_cpc', type: 'heading', label: 'CPC 입점비 정보' },
    { name: 'CPC 입점비 요청사항', type: 'textarea', required: true },
    { name: 'CPC 입점비 태깅', type: 'text', required: true, defaultValue: 'CPC_입점비', readonly: true },
    { name: 'CPC 입점비 재참여 타입', type: 'text', required: true, defaultValue: '단일참여', readonly: true },
    { name: 'CPC 입점비 광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: 'CPC 입점비 브랜드', type: 'text', required: true },
    { name: 'CPC 입점비 카테고리', type: 'select', options: newCategoryOptions, required: true }, 
    { name: 'CPC 입점비 거래처', type: 'select', optionsKey: 'clients', required: true },
    { name: 'CPC 입점비 리포트 타입', type: 'select', options: ['일반', 'CPP', 'CPS', 'CPQ', 'CPC', 'CPM', 'CPS-RewardFail'], defaultValue: 'CPC', required: true },
    { name: 'CPC 입점비 광고주 CS 담당자 이름', type: 'text', required: false },
    { name: 'CPC 입점비 광고주 CS 담당자 이메일', type: 'text', required: false },
    { name: 'CPC 입점비 본 광고 정보', type: 'textarea', required: true, placeholder: 'ID와 광고명을 기입해주세요' },
    { name: 'CPC 입점비 OS', type: 'checkbox', options: ['AOS', 'IOS', 'AOS+IOS', 'PC'], required: true },
    { name: 'CPC 입점비 광고 정산 타입', type: 'select', options: ['CPI', 'CPE', 'CPA_SNS', 'CPA_사전예약', 'CPA_회원가입', 'CPA_금융', 'CPQ', 'CPS', 'CPC'], defaultValue: 'CPC', required: true },
    { name: 'CPC 입점비 광고 집행 시작', type: 'datetime-local', required: true },
    { name: 'CPC 입점비 광고 집행 종료', type: 'datetime-local', required: true },
    { name: 'CPC 입점비 URL & 상세 랜딩 전용 URL', type: 'text', required: true },
    { name: 'CPC 입점비 소재', type: 'text', required: true },
    { name: 'CPC 입점비 라이브 시작 시간', type: 'text', defaultValue: '00:00', required: false },
    { name: 'CPC 입점비 라이브 종료 시간', type: 'text', defaultValue: '24:00', required: false },
    { name: 'CPC 입점비 광고주 앱 이름', type: 'text', required: false }, // <-- [수정] 필드 추가
    { name: 'CPC 입점비 문구 - 타이틀', type: 'text', required: true },
    { name: 'CPC 입점비 문구 - 서브', type: 'text', required: true },
    { name: 'CPC 입점비 노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true }
  ]
},



'멀티미션': {
  headerOrder: [
    '특이사항 메모장', '재참여 타입', '국내 캠페인 ID (중복 제거 필요 시 기재)', '광고주', '브랜드', '카테고리', '영업 담당자', '거래처', '리포트 타입', '광고주 CS 담당자 이름', '광고주 CS 담당자 이메일',
    '기존 글로벌 캠페인 &국내 광고 수정', '기존 글로벌 캠페인 ID', '기존 국내 상위광고 ID', '종료 일시', 'show status',
    '기존 캠페인 정보', '실적 테스트 여부', '글로벌 캠페인 ID',
    '타겟팅정보', '앱 패키지명', '앱 타겟팅 여부', 'adid 타겟팅 모수파일', '성별', '연령',
    '캠페인 완료이력 이관', '기존 국내 캠페인', '이관 국내 캠페인',
    '기존 글로벌 캠페인 세트 ID', '태깅', '광고 집행 시작', '광고 집행 종료', '타임존', '캠페인 타입', '연동사/트래커사명', '캠페인 정산 타입', '우선순위', '참여인정 유효시간', '화폐 단위', '노출 지역/국가', 'Target PubApp (Is Targeted)',
    '집행매체', 'OS', '노출 대상', 'URL_AOS', 'URL_IOS', '캠페인 오너/매니저',
    '미션 정보 붙여넣기', // 나중에 테이블로 변경될 영역
    '캠페인캡', '총물량_통합', '총물량_AOS', '총물량_IOS', '일물량_통합', '일물량_AOS', '일물량_IOS',
    '총예산_통합', '총예산_AOS', '총예산_IOS', '일예산_통합', '일예산_AOS', '일예산_IOS',
    '웹툰 비율', '시리즈 비율', '로컬', '광고 포맷', '이미지 경로', '타이틀 문구(목록)', '상단 타이틀 문구(상세)', '서브1 상단 문구(상세)', '서브2 문구', 'instruction 문구'
  ],
  fields: [
    { name: '특이사항 메모장', type: 'textarea', required: true },
    { name: '국내 캠페인 ID (중복 제거 필요 시 기재)', type: 'text', required: false },
    // 아래 8개 필드는 '국내 캠페인 ID' 입력 시 숨겨짐
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: true },
    { name: '브랜드', type: 'text', required: true },
    { name: '카테고리', type: 'select', options: newCategoryOptions, required: true }, 
    { name: '거래처', type: 'select', optionsKey: 'clients', required: true },
    { name: '광고주 CS 담당자 이름', type: 'text', required: false },
    { name: '광고주 CS 담당자 이메일', type: 'text', required: false },
    
    { name: '기존 글로벌 캠페인 &국내 광고 수정', type: 'group_checkbox', label: '기존 글로벌 캠페인 & 국내 광고 수정' },
    { name: '기존 글로벌 캠페인 ID', type: 'text', required: false, dependency: { field: '기존 글로벌 캠페인 &국내 광고 수정', showsOn: true } },
    { name: '기존 국내 상위광고 ID', type: 'text', required: false, dependency: { field: '기존 글로벌 캠페인 &국내 광고 수정', showsOn: true } },
    { name: '종료 일시', type: 'datetime-local', required: false, dependency: { field: '기존 글로벌 캠페인 &국내 광고 수정', showsOn: true } },
    { name: 'show status', type: 'select', options: ['All Users', 'Participated Users', 'Test Users', '캠페인 OFF'], required: false, dependency: { field: '기존 글로벌 캠페인 &국내 광고 수정', showsOn: true } },

    { name: '기존 캠페인 정보', type: 'group_checkbox', label: '기존 캠페인 정보' },
    { name: '실적 테스트 여부', type: 'select', options: ['테스트 O', '테스트 X'], required: false, dependency: { field: '기존 캠페인 정보', showsOn: true } },
    { name: '글로벌 캠페인 ID', type: 'text', required: false, dependency: { field: '기존 캠페인 정보', showsOn: true } },

    { name: '타겟팅정보', type: 'group_checkbox', label: '타겟팅정보' },
    { name: '앱 패키지명', type: 'text', required: false, dependency: { field: '타겟팅정보', showsOn: true } },
    { name: '앱 타겟팅 여부', type: 'select', options: ['미설치자 타겟팅', '기설치자 타겟팅'], required: false, dependency: { field: '타겟팅정보', showsOn: true } },
    { name: 'adid 타겟팅 모수파일', type: 'text', required: false, placeholder: 'adid 파일 구글 드라이브 링크 입력', dependency: { field: '타겟팅정보', showsOn: true } },
    { name: '성별', type: 'text', required: false, dependency: { field: '타겟팅정보', showsOn: true } },
    { name: '연령', type: 'text', required: false, dependency: { field: '타겟팅정보', showsOn: true } },

    { name: '캠페인 완료이력 이관', type: 'group_checkbox', label: '캠페인 완료이력 이관' },
    { name: '기존 국내 캠페인', type: 'text', required: false, dependency: { field: '캠페인 완료이력 이관', showsOn: true } },
    { name: '이관 국내 캠페인', type: 'text', required: false, dependency: { field: '캠페인 완료이력 이관', showsOn: true } },

    { name: '기존 글로벌 캠페인 세트 ID', type: 'text', required: false, placeholder: '(중복 제거 필요 시 기재)' },
    { name: '태깅', type: 'text', required: true, defaultValue: '멀티미션', readonly: true },
    { name: '광고 집행 시작', type: 'datetime-local', required: true },
    { name: '광고 집행 종료', type: 'datetime-local-unlimited', required: true },
    { name: '캠페인 타입', type: 'select', options: ['CPE S2S', 'CPA TRACKER'], required: true },
    { name: '연동사/트래커사명', type: 'text', required: true },
    { name: '참여인정 유효시간', type: 'text', required: true },
    { name: '집행매체', type: 'select', options: ['쿠키오븐 전체', '웹툰', '시리즈'], required: true },
    { name: 'OS', type: 'select', options: ['전체', 'AOS', 'IOS'], required: true },
    { name: '노출 대상', type: 'select', options: ['모든 사용자', '테스트 사용자'], required: true },
    { name: 'URL_AOS', type: 'textarea', required: false },
    { name: 'URL_IOS', type: 'textarea', required: false },
    
    { name: 'heading_mission', type: 'heading', label: '미션 정보' },
    { 
  name: '미션 정보 붙여넣기', 
  type: 'textarea', 
  required: false, 
  placeholder: '스프레드시트에서 제목 줄을 제외한 미션 데이터를 복사하여 붙여넣으세요. (항목은 탭으로 구분)',
  rows: 8  // <--- 이 줄을 추가해주세요.
},

    { name: 'heading_budget', type: 'heading', label: '물량 및 예산' },
    { name: '캠페인캡', type: 'text-unlimited', required: false },

    
    { name: '총물량_AOS', type: 'number-unlimited', required: false },
    { name: '총물량_IOS', type: 'number-unlimited', required: false },
    { name: '총물량_통합', type: 'text', required: false, readonly: true, placeholder: 'AOS/IOS 입력 시 자동 계산' },

    { name: '일물량_AOS', type: 'number-unlimited', required: false },
    { name: '일물량_IOS', type: 'number-unlimited', required: false },
    { name: '일물량_통합', type: 'text', required: false, readonly: true, placeholder: 'AOS/IOS 입력 시 자동 계산' },
    
    { name: '총예산_AOS', type: 'number-unlimited', required: false },
    { name: '총예산_IOS', type: 'number-unlimited', required: false },
    { name: '총예산_통합', type: 'text', required: false, readonly: true, placeholder: 'AOS/IOS 입력 시 자동 계산' },
    
    { name: '일예산_AOS', type: 'number-unlimited', required: false },
    { name: '일예산_IOS', type: 'number-unlimited', required: false },
    { name: '일예산_통합', type: 'text', required: false, readonly: true, placeholder: 'AOS/IOS 입력 시 자동 계산' },



    { name: '웹툰 비율', type: 'text', required: false },
    { name: '시리즈 비율', type: 'text', required: false },
    
    { name: 'heading_creative', type: 'heading', label: '소재 정보' },
    { name: '이미지 경로', type: 'text', required: true },
    { name: '타이틀 문구(목록)', type: 'text', required: true },
    { name: '상단 타이틀 문구(상세)', type: 'text', required: true },
    { name: '서브1 상단 문구(상세)', type: 'text', required: true },
    { name: '서브2 문구', type: 'textarea', required: true, defaultValue: "- 본 이벤트를 통해 최초 접속 한 경우에만 미션 참여가 인정됩니다.\n- 각 미션별 최초 1회만 참여 가능합니다.\n- 첫번째 미션 완료 후 쿠키를 지급 받지 못했다면 이후 미션을 수행하지 말고 '이용문의'를 통해 쿠키 미지급 문의를 접수해 주세요.\n- 전체 미션을 완료했거나, 참여기한이 만료되었을 경우 본 이벤트는 리스트에서 사라집니다.\n- 이벤트 상황에 따라 '참여 기한'보다 일찍 이벤트 리스트에서 노출이 중단될 수 있으나, '참여 기한' 내 게임에 접속하여 미션을 지속적으로 수행 시 쿠키가 지급됩니다.\n- 지급된 쿠키는 유효기간이 존재합니다. 하단 ‘상세 안내’를 꼭 참고 부탁드립니다." },
    { name: 'instruction 문구', type: 'textarea', required: true, defaultValue: "[참여 방법]\n1. 앱을 최초로 접속하세요\n2.  앱에서 미션을 달성하세요" }
  ]
},

'테스트 광고': {
  headerOrder: [ 
    '특이사항 메모장', '선택항목', '캠페인명', '광고주', '테스트 광고 타입',
    '광고 네트워크 연동 매체', '광고주 연동 토큰 값',  '집행매체1',
    // CPA TRACKER 필드들
    '트래커', '완료 이벤트 이름', 
    '완료 이벤트 조건(event_parameters JSON 파라미터)', // 이름 수정
    '완료 이벤트 조건(JSON)-이벤트 타입', '완료 이벤트 조건(JSON)-이벤트 이름',
    '완료 이벤트 조건(JSON)-value', '완료 이벤트 조건(JSON)-from', '완료 이벤트 조건(JSON)-to',
    '완료 이벤트 조건 (개별 파라미터)', // 이름 수정
    '완료 이벤트 조건(개별)-파라미터 타입', '완료 이벤트 조건(개별)-파라미터 이름',
    '완료 이벤트 조건(개별)-value', '완료 이벤트 조건(개별)-from', '완료 이벤트 조건(개별)-to',
    '최소 결제 금액', 'URL_기본', 'URL_AOS', 'URL_IOS', 'URL_PC',
    // 숨겨진 필드들
    '재참여 타입', '광고주 연동 토큰 값', 'OS', '총물량', '일물량', 
    '광고 집행 시작', '광고 집행 종료', '단가', '리워드'
  ],
  fields: [
    { name: '특이사항 메모장', type: 'textarea', required: true, rows: 10 },
    { name: '선택항목', type: 'select', options: ['서버 연동', 'CPA TRACKER'], required: true },
    
    // --- 공통 필드 ---
    { name: '캠페인명', type: 'text', required: true, dependency: { field: '선택항목', showsOn: ['서버 연동', 'CPA TRACKER'] } },
    { name: '광고주', type: 'select', optionsKey: 'advertisers', required: false, dependency: { field: '선택항목', showsOn: ['서버 연동', 'CPA TRACKER'] } },
    { name: '집행매체1', type: 'select', options: ['네이버페이', '쿠키오븐', '애디슨 네트워크'], required: true, dependency: { field: '선택항목', showsOn: ['서버 연동', 'CPA TRACKER'] } },
    
    // --- '서버 연동' 전용 필드 ---
    { name: '테스트 광고 타입', type: 'select', options: ['CPA S2S', 'CPI'], required: true, dependency: { field: '선택항목', showsOn: '서버 연동' } },
    { name: '광고 네트워크 연동 매체', type: 'select', options: ['TNK', 'AD POPCORN', 'PINCRUX', 'SUCOMM', 'OHC', 'IVE', 'BUZZVIL', 'ADISON DSP', '나스미디어NAP', 'CAULY', 'GreenP'], required: false, dependency: { field: '선택항목', showsOn: '서버 연동' } },

    { name: '광고주 연동 토큰 값', type: 'text', required: false, dependency: { field: '선택항목', showsOn: ['서버 연동', 'CPA TRACKER'] } },

    
    // --- 'CPA TRACKER' 전용 필드 ---
    { name: '트래커', type: 'select', options: ['Tune', 'Adbrix', 'Adjust', 'AppsFlyer', 'Kochava', 'Singular', 'Wisetracker', 'Branch', 'Airbridge', 'Adbrix Remaster', 'Ebay Linkrew'], required: true, dependency: { field: '선택항목', showsOn: 'CPA TRACKER' } },
    { name: '완료 이벤트 이름', type: 'text', required: true, dependency: { field: '선택항목', showsOn: 'CPA TRACKER' } },
    
    // ▼▼▼ [수정] name과 label을 정확한 전체 이름으로 통일 ▼▼▼
    { name: '완료 이벤트 조건(event_parameters JSON 파라미터)', type: 'group_checkbox', label: '완료 이벤트 조건(event_parameters JSON 파라미터)', dependency: { field: '선택항목', showsOn: 'CPA TRACKER' } },
    { name: '완료 이벤트 조건(JSON)-이벤트 타입', type: 'select', options: ['Value', 'Range', 'not_allowed_value'], required: true, dependency: { field: '완료 이벤트 조건(event_parameters JSON 파라미터)', showsOn: true } },
    { name: '완료 이벤트 조건(JSON)-이벤트 이름', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(event_parameters JSON 파라미터)', showsOn: true } },
    { name: '완료 이벤트 조건(JSON)-value', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(event_parameters JSON 파라미터)', showsOn: true } },
    { name: '완료 이벤트 조건(JSON)-from', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(event_parameters JSON 파라미터)', showsOn: true } },
    { name: '완료 이벤트 조건(JSON)-to', type: 'text', required: false, dependency: { field: '완료 이벤트 조건(event_parameters JSON 파라미터)', showsOn: true } },
    
    { name: '완료 이벤트 조건 (개별 파라미터)', type: 'group_checkbox', label: '완료 이벤트 조건 (개별 파라미터)', dependency: { field: '선택항목', showsOn: 'CPA TRACKER' } },
    { name: '완료 이벤트 조건(개별)-파라미터 타입', type: 'select', options: ['Value', 'Range', 'not_allowed_value'], required: true, dependency: { field: '완료 이벤트 조건 (개별 파라미터)', showsOn: true } },
    { name: '완료 이벤트 조건(개별)-파라미터 이름', type: 'text', required: false, dependency: { field: '완료 이벤트 조건 (개별 파라미터)', showsOn: true } },
    { name: '완료 이벤트 조건(개별)-value', type: 'text', required: false, dependency: { field: '완료 이벤트 조건 (개별 파라미터)', showsOn: true } },
    { name: '완료 이벤트 조건(개별)-from', type: 'text', required: false, dependency: { field: '완료 이벤트 조건 (개별 파라미터)', showsOn: true } },
    { name: '완료 이벤트 조건(개별)-to', type: 'text', required: false, dependency: { field: '완료 이벤트 조건 (개별 파라미터)', showsOn: true } },
    // ▲▲▲ [수정] ▲▲▲

    { name: '최소 결제 금액', type: 'text', required: false, dependency: { field: '선택항목', showsOn: 'CPA TRACKER' } },
    
    // --- 공통 URL 필드 ---
    { name: 'URL_기본', type: 'text', required: false, dependency: { field: '선택항목', showsOn: ['서버 연동', 'CPA TRACKER'] } },
    { name: 'URL_AOS', type: 'text', required: false, dependency: { field: '선택항목', showsOn: ['서버 연동', 'CPA TRACKER'] } },
    { name: 'URL_IOS', type: 'text', required: false, dependency: { field: '선택항목', showsOn: ['서버 연동', 'CPA TRACKER'] } },
    { name: 'URL_PC', type: 'text', required: false, dependency: { field: '선택항목', showsOn: ['서버 연동', 'CPA TRACKER'] } }
  ]
},

  },
  'dropdowns': {
      advertisers: advertisers,
      advertiserCategoryMap: advertiserCategoryMap, // [추가] 카테고리 매핑 정보 추가
      clients: clients
  }
};
return fields;
}